define("blockedTimeDetailsViewModel",["diagnosticsHub","diagnosticsHub-swimlanes","diagnosticsHub-ui","knockout","plugin-vs-v2"],((e,t,a,o,r)=>{return i={2608:e=>{const t=document.createElement("script");t.id="BlockedEventRowView",t.innerHTML=atob("PHRyIGNsYXNzPSJ0cmVlR3JpZFJvdyBibG9ja2VkRXZlbnRSb3ciIHRhYmluZGV4PSItMSIgcm9sZT0icm93IiBkYXRhLWJpbmQ9InRyZWVHcmlkUm93Rm9jdXM6ICRwYXJlbnQuZm9jdXNlZFJvdygpID09PSAkZGF0YSwgY3NzOiB7IHNlbGVjdGVkOiBzZWxlY3RlZCgpIH0iPg0KICAgIDx0ZCBjbGFzcz0ibmFtZSIgcm9sZT0iZ3JpZGNlbGwiIGRhdGEtY29sdW1uaWQ9Im5hbWUiPg0KICAgICAgICA8c3BhbiBjbGFzcz0iaW5kZW50Ij4mbmJzcDs8L3NwYW4+DQogICAgPC90ZD4NCiAgICA8dGQgY2xhc3M9ImR1cmF0aW9uIiByb2xlPSJncmlkY2VsbCIgZGF0YS1iaW5kPSJ0ZXh0OiBkdXJhdGlvbkluTXMiIGRhdGEtY29sdW1uaWQ9ImR1cmF0aW9uIj48L3RkPg0KICAgIDx0ZCBjbGFzcz0ibWF4IiByb2xlPSJncmlkY2VsbCIgZGF0YS1jb2x1bW5pZD0ibWF4Ij48L3RkPg0KPC90cj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},7348:e=>{const t=document.createElement("script");t.id="BlockedThreadRowView",t.innerHTML=atob("PHRyIGNsYXNzPSJ0cmVlR3JpZFJvdyIgdGFiaW5kZXg9Ii0xIiByb2xlPSJyb3ciIGRhdGEtYmluZD0idHJlZUdyaWRSb3dGb2N1czogJHBhcmVudC5mb2N1c2VkUm93KCkgPT09ICRkYXRhLCBjc3M6IHsgc2VsZWN0ZWQ6IHNlbGVjdGVkKCkgfSI+DQogICAgPHRkIGNsYXNzPSJuYW1lIGNvbnRhaW5lciIgcm9sZT0iZ3JpZGNlbGwiIGRhdGEtYmluZD0iY3NzOiB7IHNob3dUcmFja0FkZDogIXRyYWNrQWRkZWQoKSB9IiBkYXRhLWNvbHVtbmlkPSJuYW1lIj4NCiAgICAgICAgPGRpdiBkYXRhLWJpbmQ9InRyZWVHcmlkRXhwYW5kZXI6IGV4cGFuZGVkLCBzdHlsZTogeyB2aXNpYmlsaXR5OiBoYXNFdmVudHMgPyAndmlzaWJsZScgOiAnaGlkZGVuJyB9Ij48L2Rpdj4NCiAgICAgICAgPHNwYW4gZGF0YS1iaW5kPSJ0ZXh0OiBuYW1lIj48L3NwYW4+DQogICAgICAgIDxkaXYgY2xhc3M9ImJsb2NrZWRUaHJlYWQtYWRkVHJhY2siIGRhdGEtYmluZD0iY2xpY2s6IGFkZFRyYWNrLCB2aXNpYmxlOiAhdHJhY2tBZGRlZCgpIj48L2Rpdj4NCiAgICA8L3RkPg0KICAgIDx0ZCBjbGFzcz0iZHVyYXRpb24iIHJvbGU9ImdyaWRjZWxsIiBkYXRhLWJpbmQ9InRleHQ6IGR1cmF0aW9uSW5NcyIgZGF0YS1jb2x1bW5pZD0iZHVyYXRpb24iPjwvdGQ+DQogICAgPHRkIGNsYXNzPSJtYXgiIHJvbGU9ImdyaWRjZWxsIiBkYXRhLWJpbmQ9InRleHQ6IG1heEluTXMiIGRhdGEtY29sdW1uaWQ9Im1heCI+PC90ZD4NCjwvdHI+"),t.type="text/html",document.head.appendChild(t),e.exports={}},4816:function(e,t,a){var o,r,i=this&&this.__createBinding||(Object.create?function(e,t,a,o){void 0===o&&(o=a),Object.defineProperty(e,o,{enumerable:!0,get:function(){return t[a]}})}:function(e,t,a,o){void 0===o&&(o=a),e[o]=t[a]}),n=this&&this.__exportStar||function(e,t){for(var a in e)"default"===a||Object.prototype.hasOwnProperty.call(t,a)||i(t,e,a)};o=[a,t,a(3028),a(5639),a(4828),a(952),a(8117),a(8117)],r=function(e,t,a,o,r,i,d,s){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.getBlockedTimeDetailsViewModel=t.BlockedTimeDetailsViewModel=void 0,n(o,t);class l{constructor(){d.loadDataWarehouse().then((e=>{this._blockedTimeViewModel=new r.BlockedTimeViewModel(e),s.getViewEventManager().detailsViewReady.raiseEvent({Id:i.blockedTimeDetailsViewId()}),a.applyBindings(this)}))}get mainViewModel(){return this._blockedTimeViewModel}}let c;t.BlockedTimeDetailsViewModel=l,t.getBlockedTimeDetailsViewModel=function(){return c||(c=new l),c}}.apply(t,o),void 0===r||(e.exports=r)},4037:(e,t,a)=>{var o,r;o=[a,t,a(3028),a(8117),a(8117),a(2608)],r=function(e,t,a,o,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BlockedEventRowViewModel=void 0,t.BlockedEventRowViewModel=class{constructor(e,t){this._selected=a.observable(!1),this._expanded=a.observable(!1),this._dto=e,this._children=a.observableArray([]),this._parent=t}get parent(){return this._parent}get templateName(){return"BlockedEventRowView"}get id(){return this._dto.id}get depth(){return 1}get durationInMs(){return this._dto.durationInMs}get selected(){return this._selected}get expanded(){return this._expanded}get children(){return this._children}invoke(){r.getViewEventManager().selectionChanged.raiseEvent({position:new o.JsonTimespan(new o.BigNumber(this._dto.start.h,this._dto.start.l),new o.BigNumber(this._dto.end.h,this._dto.end.l)),isIntermittent:!1})}}}.apply(t,o),void 0===r||(e.exports=r)},7490:(e,t,a)=>{var o,r;o=[a,t,a(5226),a(3467),a(4881)],r=function(e,t,a,o,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BlockedStackFrame=void 0,t.BlockedStackFrame=class{constructor(e){this._dto=e}get name(){return this._dto.name}get label(){if(void 0===this._dto.jmcState)return"";switch(this._dto.jmcState){case r.JmcState.SystemCode:return a.Resources.getString("SystemCallLabel");case r.JmcState.LibraryCode:return a.Resources.getString("ExternalCallLabel");case r.JmcState.UserCode:default:return""}}get canGoToSource(){return this._dto.fileName&&"number"==typeof this._dto.lineNumber}goToSource(){return this.canGoToSource?(new o.BlockedTimeMarshaler).goToSource(this._dto.fileName,this._dto.lineNumber):Promise.resolve(!1)}}}.apply(t,o),void 0===r||(e.exports=r)},1336:(e,t,a)=>{var o,r;o=[a,t,a(3028),a(3467),a(4037),a(7348)],r=function(e,t,a,o,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BlockedThreadRowViewModel=void 0,t.BlockedThreadRowViewModel=class{constructor(e){this._selected=a.observable(!1),this._expanded=a.observable(!1),this._trackAdded=a.observable(!1),this._children=a.observableArray([]),this._haveLoaded=!1,this._marshaler=new o.BlockedTimeMarshaler,this._dto=e,this._marshaler.onTracksAdded.addEventListener((e=>{-1!==e.threadIds.indexOf(this._dto.threadId)&&this._trackAdded(!0)})),this._marshaler.onTracksRemoved.addEventListener((e=>{-1!==e.threadIds.indexOf(this._dto.threadId)&&this._trackAdded(!1)}))}get templateName(){return"BlockedThreadRowView"}get id(){return this._dto.threadId}get depth(){return 0}get name(){return this._dto.threadId.toString()}get durationInMs(){return this._dto.durationInMs}get maxInMs(){return this._dto.maxInMs}get trackAdded(){return this._trackAdded}get hasEvents(){return 0!==this._dto.durationInMs}get selected(){return this._selected}get expanded(){return this._expanded}get children(){return this._children}invoke(){}expand(e,t,a){let o=Promise.resolve();return this._haveLoaded||(this._haveLoaded=!0,o=e.getResult({op:"threadDetails",threadId:this._dto.threadId},a).then((e=>{const t=e.map((e=>new r.BlockedEventRowViewModel(e,this)));this._children(t)}))),this._expanded(!this._expanded()),o}addTrack(e,t){return this.trackAdded()||this._marshaler.addTrack(this._dto.threadId),!1}}}.apply(t,o),void 0===r||(e.exports=r)},5732:(e,t,a)=>{var o,r;o=[a,t,a(7490),a(952),a(1336)],r=function(e,t,a,o,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BlockedTimeDAO=void 0,t.BlockedTimeDAO=class{constructor(e){this._dataWarehouse=e}getRoots(e,t,a){return this._dataWarehouse.getFilteredData({customDomain:{Task:"Summary"}},o.blockedTimeAnalyzer(),a).then((e=>(a?.throwIfCancellationRequested(),this._currentResult=e,this._currentResult.getResult({op:"threadSummary"},a)))).then((e=>e.map((e=>new r.BlockedThreadRowViewModel(e)))))}sort(e,t,a){return Promise.resolve(e)}search(e,t,a,o,r,i,n){return Promise.resolve(null)}expand(e,t,a){return e.expand(this._currentResult,t,a)}queryStacks(e,t){return this._currentResult.getResult({op:"queryStacks",threadId:e.parent.id,eventId:e.id},t).then((e=>({blockedStack:e.blockedStack.map((e=>new a.BlockedStackFrame(e))),readyStack:e.readyStack.map((e=>new a.BlockedStackFrame(e)))})))}}}.apply(t,o),void 0===r||(e.exports=r)},3467:(e,t,a)=>{var o,r;o=[a,t,a(5226),a(8117)],r=function(e,t,a,o){"use strict";let r;Object.defineProperty(t,"__esModule",{value:!0}),t.BlockedTimeMarshaler=void 0,t.BlockedTimeMarshaler=class{constructor(){null===r&&(r=a.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.CpuSampling.BlockedTime.BlockedTimeMarshaler",{},!0)),this._onTracksAdded=new o.ObservableEvent(r,"onTracksAdded"),this._onTracksRemoved=new o.ObservableEvent(r,"onTracksRemoved")}get onTracksAdded(){return this._onTracksAdded}get onTracksRemoved(){return this._onTracksRemoved}addTrack(e){r._post("addTrack",e)}removeTrack(e){return r._call("removeTrack",e)}goToSource(e,t){return r._call("goToSource",e,t)}}}.apply(t,o),void 0===r||(e.exports=r)},7014:(e,t,a)=>{var o;o=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BlockedTimeSummaryColumnSettingsProvider=void 0,t.BlockedTimeSummaryColumnSettingsProvider=class{getColumnSettings(){return Promise.resolve([{columnId:"0",isHidden:!1,width:75},{columnId:"1",isHidden:!1,width:200},{columnId:"2",isHidden:!1,width:200}])}onColumnChanged(e){}}}.apply(t,[a,t]),void 0===o||(e.exports=o)},4828:(e,t,a)=>{var o,r;o=[a,t,a(5226),a(3028),a(4881),a(4881),a(4881),a(5732),a(7014),a(8117),a(952),a(8117)],r=function(e,t,a,o,r,i,n,d,s,l,c,u){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BlockedTimeViewModel=void 0,t.BlockedTimeViewModel=class{constructor(e){this._blockedStack=o.observableArray([]),this._readyStack=o.observableArray([]),this._dataLoadStatus=o.observable(r.DataLoadEvent.DataLoadCompleted),this._dataLoadPromise=null,this._dao=new d.BlockedTimeDAO(e);const t=new n.TreeGridHeaderViewModel([{id:"name",text:a.Resources.getString("BlockedTimeSummary_NameHeader"),hideable:!1},{id:"duration",text:a.Resources.getString("BlockedTimeSummary_DurationHeader"),hideable:!1},{id:"max",text:a.Resources.getString("BlockedTimeSummary_MaxHeader"),hideable:!1}],new s.BlockedTimeSummaryColumnSettingsProvider,"name");this._summaryViewModel=new i.TreeGridViewModel(this._dao,t,"BlockedTimeSummary_AriaLabel"),this._summaryViewModel.focusedRow.subscribe(this.onSelectionChanged.bind(this)),l.getViewEventManager().jmcEnabledStateChanged.addEventListener((()=>{this._summaryViewModel.onResultChanged(0)})),this._summaryViewModel.onResultChanged(0)}get summaryViewModel(){return this._summaryViewModel}get dataLoadStatus(){return this._dataLoadStatus}get blockedStack(){return this._blockedStack}get readyStack(){return this._readyStack}onSelectionChanged(e){if(null===e||!e.parent)return this._blockedStack([]),void this._readyStack([]);this._dataLoadCancellationTokenSource&&this._dataLoadCancellationTokenSource.cancel(),this._dataLoadCancellationTokenSource=new u.CancellationTokenSource,this._dataLoadCancellationTokenSource.token.onCancellationRequested.addEventListener((()=>{this._dataLoadStatus(r.DataLoadEvent.DataLoadCanceled)}),{once:!0});const t=e;this._dataLoadStatus(r.DataLoadEvent.DataLoadStart),this._dataLoadPromise=this._dao.queryStacks(t,this._dataLoadCancellationTokenSource.token).then((e=>{this._blockedStack(e.blockedStack),this._readyStack(e.readyStack)})).then((()=>{this._dataLoadPromise=null,this._dataLoadStatus(r.DataLoadEvent.DataLoadCompleted)}),(e=>{e.name!==c.errorNameCanceled()&&this._dataLoadStatus(r.DataLoadEvent.DataLoadFailed)}))}}}.apply(t,o),void 0===r||(e.exports=r)},952:(e,t,a)=>{var o;o=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.flameGraphViewModelMappingKey=t.flatFunctionsViewModelMappingKey=t.modulesViewModelMappingKey=t.callTreeViewModelMappingKey=t.callerCalleeViewModelMappingKey=t.functionLimit=t.defaultSampleRate=t.errorNameCanceled=t.blockedTimeDetailsViewId=t.performanceDebuggerDetailsViewId=t.collectionDetailsViewId=t.analysisDetailsViewId=t.blockedTimeAnalyzer=t.cpuSamplingAnalyzer=void 0,t.cpuSamplingAnalyzer=function(){return"DCA8B3EF-28C5-4B08-BAFC-B072F8AA9277"},t.blockedTimeAnalyzer=function(){return"3BA86369-05EE-409B-B598-BCCDFA4EFE2F"},t.analysisDetailsViewId=function(){return"7D95F423-6D5E-488C-B3A9-169D6D297D5C"},t.collectionDetailsViewId=function(){return"DDEDFB2B-8979-4CA9-BED3-7A3E4C495F1C"},t.performanceDebuggerDetailsViewId=function(){return"47660699-1BCE-4442-AEA7-A520683BDA66"},t.blockedTimeDetailsViewId=function(){return"CA734335-A674-41E2-BC61-98564E300942"},t.errorNameCanceled=function(){return"Canceled"},t.defaultSampleRate=function(){return 1e3},t.functionLimit=function(){return 5},t.callerCalleeViewModelMappingKey=function(){return"CallerCalleeView"},t.callTreeViewModelMappingKey=function(){return"CallTreeView"},t.modulesViewModelMappingKey=function(){return"ModulesView"},t.flatFunctionsViewModelMappingKey=function(){return"FlatFunctionsView"},t.flameGraphViewModelMappingKey=function(){return"FlameGraphView"}}.apply(t,[a,t]),void 0===o||(e.exports=o)},5639:(e,t,a)=>{var o,r;o=[a,t,a(8558)],r=function(e,t,a){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),window.CpuSamplingUI_onAfterDomInsert=a.onAfterDomInsert}.apply(t,o),void 0===r||(e.exports=r)},7886:(e,t,a)=>{var o;o=function(e,t){"use strict";var a,o,r,i,n,d,s,l;Object.defineProperty(t,"__esModule",{value:!0}),t.PerformanceSessionEntryPoint=t.SortColumn=t.CpuToolView=t.ResultStage=t.ResultNotStartedReason=t.ResultPreparationStatus=t.ActivityType=t.ResultTaskType=void 0,(l=t.ResultTaskType||(t.ResultTaskType={}))[l.Expand=1]="Expand",l[l.Search=2]="Search",l[l.GetData=3]="GetData",l[l.Sort=4]="Sort",l[l.ExpandHotPath=5]="ExpandHotPath",l[l.TopFunctions=6]="TopFunctions",l[l.GetNodePath=7]="GetNodePath",l[l.TopInsights=8]="TopInsights",l[l.Autocomplete=9]="Autocomplete",l[l.UpdateRoot=10]="UpdateRoot",l[l.InsightHelp=11]="InsightHelp",(s=t.ActivityType||(t.ActivityType={}))[s.Unknown=0]="Unknown",s[s.ThreadRun=1]="ThreadRun",s[s.AsyncTask=2]="AsyncTask",(d=t.ResultPreparationStatus||(t.ResultPreparationStatus={}))[d.NotStarted=0]="NotStarted",d[d.InProgress=1]="InProgress",d[d.Completed=2]="Completed",d[d.Canceled=3]="Canceled",d[d.Failed=4]="Failed",(n=t.ResultNotStartedReason||(t.ResultNotStartedReason={}))[n.Unknown=0]="Unknown",n[n.NoValidTimeSelection=1]="NoValidTimeSelection",n[n.NoValidThreadSelection=2]="NoValidThreadSelection",n[n.ToolIsDisabled=3]="ToolIsDisabled",n[n.TargetRunningUnderDebugger=4]="TargetRunningUnderDebugger",(i=t.ResultStage||(t.ResultStage={}))[i.Unknown=0]="Unknown",i[i.Threads=1]="Threads",i[i.Sampling=2]="Sampling",(r=t.CpuToolView||(t.CpuToolView={}))[r.FlatFunctionsView=1]="FlatFunctionsView",r[r.CallerCalleeView=2]="CallerCalleeView",r[r.CallTreeView=3]="CallTreeView",r[r.ModulesView=4]="ModulesView",r[r.FlameGraphView=5]="FlameGraphView",(o=t.SortColumn||(t.SortColumn={}))[o.Id=1]="Id",o[o.FunctionName=2]="FunctionName",o[o.TotalSamples=3]="TotalSamples",o[o.SelfSamples=4]="SelfSamples",o[o.ModuleName=5]="ModuleName",o[o.CategoryName=6]="CategoryName",o[o.CallCount=7]="CallCount",(a=t.PerformanceSessionEntryPoint||(t.PerformanceSessionEntryPoint={}))[a.Profiling=0]="Profiling",a[a.PerformanceDebugger=1]="PerformanceDebugger"}.apply(t,[a,t]),void 0===o||(e.exports=o)},8558:(e,t,a)=>{var o,r;o=[a,t,a(5226),a(3028),a(7886),a(4881),a(8117),a(2560)],r=function(e,t,a,o,r,i,n,d){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.onAfterDomInsert=t.localizeNumber=t.areToolContextsEqual=t.areTimespansEqual=t.areBigNumbersEqual=t.numberComparator=t.getSortFunction=void 0;let s={};a.Culture.addEventListener("culturechanged",(()=>{s={}})),t.getSortFunction=function(e,t){switch(e){case r.SortColumn.Id:return i.SortFunctions.numericSort("id",t);case r.SortColumn.FunctionName:return i.SortFunctions.stringSort("name",t);case r.SortColumn.SelfSamples:return i.SortFunctions.numericSort("selfSamples",t);case r.SortColumn.TotalSamples:return i.SortFunctions.numericSort("totalSamples",t);case r.SortColumn.ModuleName:return i.SortFunctions.stringSort("moduleName",t);case r.SortColumn.CategoryName:return i.SortFunctions.stringSort("categoryName",t);case r.SortColumn.CallCount:return i.SortFunctions.numericSort("callCount",t);default:throw n.Assert.fail(`Unknown sort column: ${r.SortColumn[e]}`),new Error(`Unknown sort column: ${r.SortColumn[e]}`)}},t.numberComparator=function(e,t){return e-t},t.areBigNumbersEqual=function(e,t){return!e&&!t||e&&t&&e.h===t.h&&e.l===t.l},t.areTimespansEqual=function(e,t){return!e&&!t||e&&t&&e.equals(t)},t.areToolContextsEqual=function(e,t){return!e&&!t||e&&t&&e.rowId===t.rowId&&e.rowType===t.rowType},t.localizeNumber=function(e,t){const o=JSON.stringify(t||{});let r=s[o];if(!r){const e=new Intl.NumberFormat(a.Culture.formatRegion,t);r=t=>e.format(t),s[o]=r}return r(e)},t.onAfterDomInsert=function(){const e=document.getElementById("mainToolbar"),t=o.utils.domData.get(e,"mediaQuery");if(t){const a=o.utils.domData.get(e,"mediaQueryListener");t.removeListener(a)}let a=45;const r=e.children;for(let e=0;e<r.length;e++)a+=r.item(e).offsetWidth;const i=t=>{t.matches?e.classList.add("limitedSpace"):e.classList.remove("limitedSpace")},n=window.matchMedia(d.Utilities.formatString("(max-width: {0}px)",a.toString()));i(n),n.addListener(i),o.utils.domData.set(e,"mediaQuery",n),o.utils.domData.set(e,"mediaQueryListener",i)}}.apply(t,o),void 0===r||(e.exports=r)},8117:t=>{"use strict";t.exports=e},2560:e=>{"use strict";e.exports=t},4881:e=>{"use strict";e.exports=a},3028:e=>{"use strict";e.exports=o},5226:e=>{"use strict";e.exports=r}},n={},function e(t){var a=n[t];if(void 0!==a)return a.exports;var o=n[t]={exports:{}};return i[t].call(o.exports,o,o.exports,e),o.exports}(4816);var i,n}));
// SIG // Begin signature block
// SIG // MIIoNwYJKoZIhvcNAQcCoIIoKDCCKCQCAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // p/vvdhrA2eiGNSLIZaUPK8udW4zltPLW/4eNMoDtOD2g
// SIG // gg2FMIIGAzCCA+ugAwIBAgITMwAAA64tNVHIU49VHQAA
// SIG // AAADrjANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTIzMTExNjE5MDg1OVoX
// SIG // DTI0MTExNDE5MDg1OVowdDELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjEeMBwGA1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // 9CD8pjY3wxCoPmMhOkow7ycCltfqYnqk4wGNApzh2dTY
// SIG // +YqxozWTzJUOB38VxsgFQmXBFhOMdrGYGpvO9kdbNPkw
// SIG // HpTrW6hZqFuLLiRwGKEx4ZM5zVSqbHJuX2fPfUJ0Xmb+
// SIG // VrVsGw/BwBV2zz0rVtiSgqj3GeeGOsG7llfWyrSjyJqm
// SIG // 5DHE3o04BAI/NuhkHOv04euiqJGvHFCL8+fXvyD9OAxq
// SIG // 4fcJKtoyBb0PBA3oMNQeCsiUyLO+voZqVTOUsAWY0bN5
// SIG // YjkK4nq5DVaNdVrrowd5AX9gmz6D/TJTssns6pDCG00Y
// SIG // +Dh3ipWpnVmkhYcByyUSEKX3PLC8DkiAQQIDAQABo4IB
// SIG // gjCCAX4wHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYB
// SIG // BQUHAwMwHQYDVR0OBBYEFIcf73Spl4cHOFoll27H9COd
// SIG // 4fE/MFQGA1UdEQRNMEukSTBHMS0wKwYDVQQLEyRNaWNy
// SIG // b3NvZnQgSXJlbGFuZCBPcGVyYXRpb25zIExpbWl0ZWQx
// SIG // FjAUBgNVBAUTDTIzMDAxMis1MDE4MzYwHwYDVR0jBBgw
// SIG // FoAUSG5k5VAF04KqFzc3IrVtqMp1ApUwVAYDVR0fBE0w
// SIG // SzBJoEegRYZDaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
// SIG // L3BraW9wcy9jcmwvTWljQ29kU2lnUENBMjAxMV8yMDEx
// SIG // LTA3LTA4LmNybDBhBggrBgEFBQcBAQRVMFMwUQYIKwYB
// SIG // BQUHMAKGRWh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9w
// SIG // a2lvcHMvY2VydHMvTWljQ29kU2lnUENBMjAxMV8yMDEx
// SIG // LTA3LTA4LmNydDAMBgNVHRMBAf8EAjAAMA0GCSqGSIb3
// SIG // DQEBCwUAA4ICAQBqyWA1Eu7PKNMjaaxl0V7gJ0XBysUo
// SIG // xZluMHJXFE2LEGZIZ2zMLYVjOnAGG/4dluRjSrZZo/8v
// SIG // wk4Xt8v6NBB9ofo8H1P/XidHytWTv9lg9MYu++6lPmu5
// SIG // fCozD3cI2NLZPW2BBhGX2D0R8tQBj0FbmZRuIucpiQ7D
// SIG // K3CHKlfKcc7MP8pPzuMv55Tox8+KFQD1NG6+bfbYA/BN
// SIG // PBkg4tyOh+exbaHfcNuodDJUIjq9dF6oa+Yjy0u0pUMI
// SIG // /B1t+8m6rJo0KSoZlrpesYl0jRhpt+hmqx8uENXoGJcY
// SIG // ZVJ5N2Skq90LViKNRhi9N4U+e8c4y9uXyomUF/6viCPJ
// SIG // 7huTNEJo75ehIJba+IWd3txUEc0R3y6DT6txC6cW1nR/
// SIG // LTbo9I/8fQq538G5IvJ+e5iSiOSVVkVk0i5m03Awy5E2
// SIG // ZSS4PVdQSCcFxmN4tpEfYuR7AAy/GJVtIDFlUpSgdXok
// SIG // pSui5hYtK1R9enXXvo+U/xGkLRc+qp4De3dZbzu7pOq7
// SIG // V/jCyhuCw0bEIAU4urCGIip7TI6GBRzD7yPzjFIqeZY7
// SIG // S4rVW5BRn2oEqpm8Su6yTIQvMIk8x2pwYNUa2339Z4gW
// SIG // 5xW21eFA5mLpo7NRSKRQms5OgAA18aCgqOU7Ds0h6q/Y
// SIG // B4BmEAtoTMl/TBiyKaMGAlEcdy+5FIhmzojMGjCCB3ow
// SIG // ggVioAMCAQICCmEOkNIAAAAAAAMwDQYJKoZIhvcNAQEL
// SIG // BQAwgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNo
// SIG // aW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQK
// SIG // ExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xMjAwBgNVBAMT
// SIG // KU1pY3Jvc29mdCBSb290IENlcnRpZmljYXRlIEF1dGhv
// SIG // cml0eSAyMDExMB4XDTExMDcwODIwNTkwOVoXDTI2MDcw
// SIG // ODIxMDkwOVowfjELMAkGA1UEBhMCVVMxEzARBgNVBAgT
// SIG // Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAc
// SIG // BgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEoMCYG
// SIG // A1UEAxMfTWljcm9zb2Z0IENvZGUgU2lnbmluZyBQQ0Eg
// SIG // MjAxMTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
// SIG // ggIBAKvw+nIQHC6t2G6qghBNNLrytlghn0IbKmvpWlCq
// SIG // uAY4GgRJun/DDB7dN2vGEtgL8DjCmQawyDnVARQxQtOJ
// SIG // DXlkh36UYCRsr55JnOloXtLfm1OyCizDr9mpK656Ca/X
// SIG // llnKYBoF6WZ26DJSJhIv56sIUM+zRLdd2MQuA3WraPPL
// SIG // bfM6XKEW9Ea64DhkrG5kNXimoGMPLdNAk/jj3gcN1Vx5
// SIG // pUkp5w2+oBN3vpQ97/vjK1oQH01WKKJ6cuASOrdJXtjt
// SIG // 7UORg9l7snuGG9k+sYxd6IlPhBryoS9Z5JA7La4zWMW3
// SIG // Pv4y07MDPbGyr5I4ftKdgCz1TlaRITUlwzluZH9TupwP
// SIG // rRkjhMv0ugOGjfdf8NBSv4yUh7zAIXQlXxgotswnKDgl
// SIG // mDlKNs98sZKuHCOnqWbsYR9q4ShJnV+I4iVd0yFLPlLE
// SIG // tVc/JAPw0XpbL9Uj43BdD1FGd7P4AOG8rAKCX9vAFbO9
// SIG // G9RVS+c5oQ/pI0m8GLhEfEXkwcNyeuBy5yTfv0aZxe/C
// SIG // HFfbg43sTUkwp6uO3+xbn6/83bBm4sGXgXvt1u1L50kp
// SIG // pxMopqd9Z4DmimJ4X7IvhNdXnFy/dygo8e1twyiPLI9A
// SIG // N0/B4YVEicQJTMXUpUMvdJX3bvh4IFgsE11glZo+TzOE
// SIG // 2rCIF96eTvSWsLxGoGyY0uDWiIwLAgMBAAGjggHtMIIB
// SIG // 6TAQBgkrBgEEAYI3FQEEAwIBADAdBgNVHQ4EFgQUSG5k
// SIG // 5VAF04KqFzc3IrVtqMp1ApUwGQYJKwYBBAGCNxQCBAwe
// SIG // CgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB
// SIG // /wQFMAMBAf8wHwYDVR0jBBgwFoAUci06AjGQQ7kUBU7h
// SIG // 6qfHMdEjiTQwWgYDVR0fBFMwUTBPoE2gS4ZJaHR0cDov
// SIG // L2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVj
// SIG // dHMvTWljUm9vQ2VyQXV0MjAxMV8yMDExXzAzXzIyLmNy
// SIG // bDBeBggrBgEFBQcBAQRSMFAwTgYIKwYBBQUHMAKGQmh0
// SIG // dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMv
// SIG // TWljUm9vQ2VyQXV0MjAxMV8yMDExXzAzXzIyLmNydDCB
// SIG // nwYDVR0gBIGXMIGUMIGRBgkrBgEEAYI3LgMwgYMwPwYI
// SIG // KwYBBQUHAgEWM2h0dHA6Ly93d3cubWljcm9zb2Z0LmNv
// SIG // bS9wa2lvcHMvZG9jcy9wcmltYXJ5Y3BzLmh0bTBABggr
// SIG // BgEFBQcCAjA0HjIgHQBMAGUAZwBhAGwAXwBwAG8AbABp
// SIG // AGMAeQBfAHMAdABhAHQAZQBtAGUAbgB0AC4gHTANBgkq
// SIG // hkiG9w0BAQsFAAOCAgEAZ/KGpZjgVHkaLtPYdGcimwuW
// SIG // EeFjkplCln3SeQyQwWVfLiw++MNy0W2D/r4/6ArKO79H
// SIG // qaPzadtjvyI1pZddZYSQfYtGUFXYDJJ80hpLHPM8QotS
// SIG // 0LD9a+M+By4pm+Y9G6XUtR13lDni6WTJRD14eiPzE32m
// SIG // kHSDjfTLJgJGKsKKELukqQUMm+1o+mgulaAqPyprWElj
// SIG // HwlpblqYluSD9MCP80Yr3vw70L01724lruWvJ+3Q3fMO
// SIG // r5kol5hNDj0L8giJ1h/DMhji8MUtzluetEk5CsYKwsat
// SIG // ruWy2dsViFFFWDgycScaf7H0J/jeLDogaZiyWYlobm+n
// SIG // t3TDQAUGpgEqKD6CPxNNZgvAs0314Y9/HG8VfUWnduVA
// SIG // KmWjw11SYobDHWM2l4bf2vP48hahmifhzaWX0O5dY0Hj
// SIG // Wwechz4GdwbRBrF1HxS+YWG18NzGGwS+30HHDiju3mUv
// SIG // 7Jf2oVyW2ADWoUa9WfOXpQlLSBCZgB/QACnFsZulP0V3
// SIG // HjXG0qKin3p6IvpIlR+r+0cjgPWe+L9rt0uX4ut1eBrs
// SIG // 6jeZeRhL/9azI2h15q/6/IvrC4DqaTuv/DDtBEyO3991
// SIG // bWORPdGdVk5Pv4BXIqF4ETIheu9BCrE/+6jMpF3BoYib
// SIG // V3FWTkhFwELJm3ZbCoBIa/15n8G9bW1qyVJzEw16UM0x
// SIG // ghoKMIIaBgIBATCBlTB+MQswCQYDVQQGEwJVUzETMBEG
// SIG // A1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
// SIG // ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBTaWduaW5n
// SIG // IFBDQSAyMDExAhMzAAADri01UchTj1UdAAAAAAOuMA0G
// SIG // CWCGSAFlAwQCAQUAoIGuMBkGCSqGSIb3DQEJAzEMBgor
// SIG // BgEEAYI3AgEEMBwGCisGAQQBgjcCAQsxDjAMBgorBgEE
// SIG // AYI3AgEVMC8GCSqGSIb3DQEJBDEiBCBYONbkNLdVKvzM
// SIG // 9r9nfY1Q1URY+4fBhF6nR7ArOioSaDBCBgorBgEEAYI3
// SIG // AgEMMTQwMqAUgBIATQBpAGMAcgBvAHMAbwBmAHShGoAY
// SIG // aHR0cDovL3d3dy5taWNyb3NvZnQuY29tMA0GCSqGSIb3
// SIG // DQEBAQUABIIBAMGuVRnF9S+/BJNbSWcv57nJauTLu6DL
// SIG // Jvyv8Ar2IcUeGVVRvG3GSuikbIzuCnN1tCd52VHutnGr
// SIG // srJ0ldevuWq7bfHtHylfBBQQ0bsV6rhsRrB5JCUgE+tL
// SIG // 1SmxS65ywg1IoISN2AElb9wzLktKJuM9hwnhxke/NKMW
// SIG // Cyga0ve2kMBxdrxyDGQKZwRt6EBRGLfV9F2LR0QmV3Je
// SIG // fQ8aSS0lmuUmfAiWpdOwzlmi3AGyol4NdBO6L83SuSUs
// SIG // o3+5OtGnW04a/+vdGaf/TJXuy8ZQ+fKt6GuwJJt1GN3n
// SIG // OgCHWN8iahaX9fjnpoFQhT5mp+DOnJE7lu9xh/6vlSmS
// SIG // KumhgheUMIIXkAYKKwYBBAGCNwMDATGCF4Awghd8Bgkq
// SIG // hkiG9w0BBwKgghdtMIIXaQIBAzEPMA0GCWCGSAFlAwQC
// SIG // AQUAMIIBUgYLKoZIhvcNAQkQAQSgggFBBIIBPTCCATkC
// SIG // AQEGCisGAQQBhFkKAwEwMTANBglghkgBZQMEAgEFAAQg
// SIG // 2JzMJq9f/UzR0fjAkoKFyKzkM7BI+UBXU9oKxZOgCD0C
// SIG // BmV69mFkqhgTMjAyNDAxMDMxNjAzMTUuMDk4WjAEgAIB
// SIG // 9KCB0aSBzjCByzELMAkGA1UEBhMCVVMxEzARBgNVBAgT
// SIG // Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAc
// SIG // BgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjElMCMG
// SIG // A1UECxMcTWljcm9zb2Z0IEFtZXJpY2EgT3BlcmF0aW9u
// SIG // czEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNOOkEwMDAt
// SIG // MDVFMC1EOTQ3MSUwIwYDVQQDExxNaWNyb3NvZnQgVGlt
// SIG // ZS1TdGFtcCBTZXJ2aWNloIIR6jCCByAwggUIoAMCAQIC
// SIG // EzMAAAHQdwiq76MXxt0AAQAAAdAwDQYJKoZIhvcNAQEL
// SIG // BQAwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hp
// SIG // bmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
// SIG // FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMd
// SIG // TWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAwHhcN
// SIG // MjMwNTI1MTkxMjE0WhcNMjQwMjAxMTkxMjE0WjCByzEL
// SIG // MAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
// SIG // EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jv
// SIG // c29mdCBDb3Jwb3JhdGlvbjElMCMGA1UECxMcTWljcm9z
// SIG // b2Z0IEFtZXJpY2EgT3BlcmF0aW9uczEnMCUGA1UECxMe
// SIG // blNoaWVsZCBUU1MgRVNOOkEwMDAtMDVFMC1EOTQ3MSUw
// SIG // IwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2
// SIG // aWNlMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
// SIG // AgEA3zJX59+X7zNFwFEpiOaohtFMT4tuR5EsgYM5N86W
// SIG // Dt9dXdThBBc9EKQCtt7NXSRa4weYA/kjMOc+hMMQuAq1
// SIG // 1PSmkOFjR6h64Vn7aYKNzJCXsfX65jvTJXVH41BuerCF
// SIG // umFRemI1/va09SQ3Qgx26OZ2YmrDIoBimsBm9h6g+/5I
// SIG // 0Ueu0b1Ye0OJ2rQFbuOmX+TC74kdMTeXDRttMcAcILbW
// SIG // mBJOV5VC2gR+Tp189nlqCMfkowzuwbeQbgAVmPEr5kUH
// SIG // wck9nKaRM047f37NMaeAdXAB1Q8JRsGbr/UX3N53XcYB
// SIG // aygPDFh2yRdPmllFGCAUfBctoLhVR6B3js3uyLG8r0a2
// SIG // sf//N4GKqPHOWf9f7u5Iy3E4IqYsmfFxEbCxBAieaMdQ
// SIG // QS2OgI5m4AMw3TZdi3no/qiG3Qa/0lLyhAvl8OMYxTDk
// SIG // 1FVilnprdpIcJ3VHwTUezc7tc/S9Fr+0wGP7/r+qTYQH
// SIG // qITzAhSXPmpOrjA/Eyks1hY8OWgA5Jg/ZhrgvOsr0ipC
// SIG // CODGss6FHbHk9J35PGNHz47XcNlp3o5esyx7mF8HA2rt
// SIG // jtQzLqInnTVY0xd+1BJmE/qMQvzhV1BjwxELfbc4G0fY
// SIG // PBy7VHxHljrDhA+cYG+a8Mn7yLLOx/3HRxXCIiHM80IG
// SIG // J7C8hBnqaGQ5CoUjEeXggeinL/0CAwEAAaOCAUkwggFF
// SIG // MB0GA1UdDgQWBBQz4QGFktKAPpTrSE34ybcpdJJ0UTAf
// SIG // BgNVHSMEGDAWgBSfpxVdAF5iXYP05dJlpxtTNRnpcjBf
// SIG // BgNVHR8EWDBWMFSgUqBQhk5odHRwOi8vd3d3Lm1pY3Jv
// SIG // c29mdC5jb20vcGtpb3BzL2NybC9NaWNyb3NvZnQlMjBU
// SIG // aW1lLVN0YW1wJTIwUENBJTIwMjAxMCgxKS5jcmwwbAYI
// SIG // KwYBBQUHAQEEYDBeMFwGCCsGAQUFBzAChlBodHRwOi8v
// SIG // d3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NlcnRzL01p
// SIG // Y3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0ElMjAyMDEw
// SIG // KDEpLmNydDAMBgNVHRMBAf8EAjAAMBYGA1UdJQEB/wQM
// SIG // MAoGCCsGAQUFBwMIMA4GA1UdDwEB/wQEAwIHgDANBgkq
// SIG // hkiG9w0BAQsFAAOCAgEAl4fnJApGWgNOkjVvqsbUvYB0
// SIG // KeMexvoHYpJ4CiLRK/KLZFyK5lj2K2q0VgZWPdZahoop
// SIG // R8iJWd4jQVG2jRJmigBjGeWHEuyGVCj2qtY1NJrMpfvK
// SIG // INLfQv2duvmrcd77IR6xULkoMEx2Vac7+5PAmJwWKMXY
// SIG // SNbhoah+feZqi77TLMRDf9bKO1Pm91Oiwq8ubsMHM+fo
// SIG // /Do9BlF92/omYPgLNMUzek9EGvATXnPy8HMqmDRGjJFt
// SIG // lQCq5ob1h/Dgg03F4DjZ5wAUBwX1yv3ywGxxRktVzTra
// SIG // +tv4mhwRgJKwhpegYvD38LOn7PsPrBPa94V/VYNILETK
// SIG // B0bjGol7KxphrLmJy59wME4LjGrcPUfFObybVkpbtQhT
// SIG // uT9CxL0EIjGddrEErEAJDQ07Pa041TY4yFIKGelzzMZX
// SIG // DyA3I8cPG33m+MuMAMTNkUaFnMaZMfuiCH9i/m+4Cx7Q
// SIG // cVwlieWzFu1sFAti5bW7q1MAb9EoI6Q7WxKsP7g4FgXq
// SIG // wk/mbctzXPeu4hmkI8mEB+h/4fV3PLJptp+lY8kkcdrM
// SIG // J1t4a+kMet1P8WPRy+hTYaxohRA+2USq58L717zFUFCB
// SIG // JAexlBHjeoXmPIBy7dIy1d8sw4kAPEfKeWBoBgFbfTBM
// SIG // IACTWNYh7x//L84SUmRTZB/LL0c7Tv4t07yq42/GccIw
// SIG // ggdxMIIFWaADAgECAhMzAAAAFcXna54Cm0mZAAAAAAAV
// SIG // MA0GCSqGSIb3DQEBCwUAMIGIMQswCQYDVQQGEwJVUzET
// SIG // MBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVk
// SIG // bW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0
// SIG // aW9uMTIwMAYDVQQDEylNaWNyb3NvZnQgUm9vdCBDZXJ0
// SIG // aWZpY2F0ZSBBdXRob3JpdHkgMjAxMDAeFw0yMTA5MzAx
// SIG // ODIyMjVaFw0zMDA5MzAxODMyMjVaMHwxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1l
// SIG // LVN0YW1wIFBDQSAyMDEwMIICIjANBgkqhkiG9w0BAQEF
// SIG // AAOCAg8AMIICCgKCAgEA5OGmTOe0ciELeaLL1yR5vQ7V
// SIG // gtP97pwHB9KpbE51yMo1V/YBf2xK4OK9uT4XYDP/XE/H
// SIG // ZveVU3Fa4n5KWv64NmeFRiMMtY0Tz3cywBAY6GB9alKD
// SIG // RLemjkZrBxTzxXb1hlDcwUTIcVxRMTegCjhuje3XD9gm
// SIG // U3w5YQJ6xKr9cmmvHaus9ja+NSZk2pg7uhp7M62AW36M
// SIG // EBydUv626GIl3GoPz130/o5Tz9bshVZN7928jaTjkY+y
// SIG // OSxRnOlwaQ3KNi1wjjHINSi947SHJMPgyY9+tVSP3PoF
// SIG // VZhtaDuaRr3tpK56KTesy+uDRedGbsoy1cCGMFxPLOJi
// SIG // ss254o2I5JasAUq7vnGpF1tnYN74kpEeHT39IM9zfUGa
// SIG // RnXNxF803RKJ1v2lIH1+/NmeRd+2ci/bfV+Autuqfjbs
// SIG // Nkz2K26oElHovwUDo9Fzpk03dJQcNIIP8BDyt0cY7afo
// SIG // mXw/TNuvXsLz1dhzPUNOwTM5TI4CvEJoLhDqhFFG4tG9
// SIG // ahhaYQFzymeiXtcodgLiMxhy16cg8ML6EgrXY28MyTZk
// SIG // i1ugpoMhXV8wdJGUlNi5UPkLiWHzNgY1GIRH29wb0f2y
// SIG // 1BzFa/ZcUlFdEtsluq9QBXpsxREdcu+N+VLEhReTwDwV
// SIG // 2xo3xwgVGD94q0W29R6HXtqPnhZyacaue7e3PmriLq0C
// SIG // AwEAAaOCAd0wggHZMBIGCSsGAQQBgjcVAQQFAgMBAAEw
// SIG // IwYJKwYBBAGCNxUCBBYEFCqnUv5kxJq+gpE8RjUpzxD/
// SIG // LwTuMB0GA1UdDgQWBBSfpxVdAF5iXYP05dJlpxtTNRnp
// SIG // cjBcBgNVHSAEVTBTMFEGDCsGAQQBgjdMg30BATBBMD8G
// SIG // CCsGAQUFBwIBFjNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
// SIG // b20vcGtpb3BzL0RvY3MvUmVwb3NpdG9yeS5odG0wEwYD
// SIG // VR0lBAwwCgYIKwYBBQUHAwgwGQYJKwYBBAGCNxQCBAwe
// SIG // CgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB
// SIG // /wQFMAMBAf8wHwYDVR0jBBgwFoAU1fZWy4/oolxiaNE9
// SIG // lJBb186aGMQwVgYDVR0fBE8wTTBLoEmgR4ZFaHR0cDov
// SIG // L2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVj
// SIG // dHMvTWljUm9vQ2VyQXV0XzIwMTAtMDYtMjMuY3JsMFoG
// SIG // CCsGAQUFBwEBBE4wTDBKBggrBgEFBQcwAoY+aHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNS
// SIG // b29DZXJBdXRfMjAxMC0wNi0yMy5jcnQwDQYJKoZIhvcN
// SIG // AQELBQADggIBAJ1VffwqreEsH2cBMSRb4Z5yS/ypb+pc
// SIG // FLY+TkdkeLEGk5c9MTO1OdfCcTY/2mRsfNB1OW27DzHk
// SIG // wo/7bNGhlBgi7ulmZzpTTd2YurYeeNg2LpypglYAA7AF
// SIG // vonoaeC6Ce5732pvvinLbtg/SHUB2RjebYIM9W0jVOR4
// SIG // U3UkV7ndn/OOPcbzaN9l9qRWqveVtihVJ9AkvUCgvxm2
// SIG // EhIRXT0n4ECWOKz3+SmJw7wXsFSFQrP8DJ6LGYnn8Atq
// SIG // gcKBGUIZUnWKNsIdw2FzLixre24/LAl4FOmRsqlb30mj
// SIG // dAy87JGA0j3mSj5mO0+7hvoyGtmW9I/2kQH2zsZ0/fZM
// SIG // cm8Qq3UwxTSwethQ/gpY3UA8x1RtnWN0SCyxTkctwRQE
// SIG // cb9k+SS+c23Kjgm9swFXSVRk2XPXfx5bRAGOWhmRaw2f
// SIG // pCjcZxkoJLo4S5pu+yFUa2pFEUep8beuyOiJXk+d0tBM
// SIG // drVXVAmxaQFEfnyhYWxz/gq77EFmPWn9y8FBSX5+k77L
// SIG // +DvktxW/tM4+pTFRhLy/AsGConsXHRWJjXD+57XQKBqJ
// SIG // C4822rpM+Zv/Cuk0+CQ1ZyvgDbjmjJnW4SLq8CdCPSWU
// SIG // 5nR0W2rRnj7tfqAxM328y+l7vzhwRNGQ8cirOoo6CGJ/
// SIG // 2XBjU02N7oJtpQUQwXEGahC0HVUzWLOhcGbyoYIDTTCC
// SIG // AjUCAQEwgfmhgdGkgc4wgcsxCzAJBgNVBAYTAlVTMRMw
// SIG // EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
// SIG // b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
// SIG // b24xJTAjBgNVBAsTHE1pY3Jvc29mdCBBbWVyaWNhIE9w
// SIG // ZXJhdGlvbnMxJzAlBgNVBAsTHm5TaGllbGQgVFNTIEVT
// SIG // TjpBMDAwLTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9z
// SIG // b2Z0IFRpbWUtU3RhbXAgU2VydmljZaIjCgEBMAcGBSsO
// SIG // AwIaAxUAvLfIU/CilF/dZVORakT/Qn7vTImggYMwgYCk
// SIG // fjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
// SIG // Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
// SIG // TWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1N
// SIG // aWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDANBgkq
// SIG // hkiG9w0BAQsFAAIFAOk/0GkwIhgPMjAyNDAxMDMxMjI0
// SIG // MDlaGA8yMDI0MDEwNDEyMjQwOVowdDA6BgorBgEEAYRZ
// SIG // CgQBMSwwKjAKAgUA6T/QaQIBADAHAgEAAgIm/DAHAgEA
// SIG // AgIT9DAKAgUA6UEh6QIBADA2BgorBgEEAYRZCgQCMSgw
// SIG // JjAMBgorBgEEAYRZCgMCoAowCAIBAAIDB6EgoQowCAIB
// SIG // AAIDAYagMA0GCSqGSIb3DQEBCwUAA4IBAQCOM5+59aIt
// SIG // fKX139UTF/Lk9W7aM6Lwc05srUPlzJnSdan2isZ1McpH
// SIG // JCPaXd7Cb9ZOw+8W/RXkDJmP1mEcJst5visqpSuDwDUG
// SIG // FDJ9ntWaX4mDat0FDn5rrSLA+3H6+FeD8bzIfNTDl7r3
// SIG // E7xVhPEuFC8ia08Zejw3rdFWxn+STN95IHIClnHvvlhi
// SIG // GJHPuJdr627yI4SAv6KNRQeco9Z+HGpZo8ibtnxIdeOI
// SIG // iJQc6HHr+ay5tdg1IiukJXlmC/FfTq/bXHUGbZX1Fhhf
// SIG // wd/b0MFyEHxO3+WSrGIvXlV6li4MN/1IjSUGhCxmISBm
// SIG // 1HSYw8q4GSdh2FVKf12raZu+MYIEDTCCBAkCAQEwgZMw
// SIG // fDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
// SIG // b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
// SIG // Y3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWlj
// SIG // cm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTACEzMAAAHQ
// SIG // dwiq76MXxt0AAQAAAdAwDQYJYIZIAWUDBAIBBQCgggFK
// SIG // MBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAvBgkq
// SIG // hkiG9w0BCQQxIgQgoK34i6aPUo4hK+wfLrIyTOPd3DOf
// SIG // OOhyCVHSyyspJe0wgfoGCyqGSIb3DQEJEAIvMYHqMIHn
// SIG // MIHkMIG9BCAIlUAGX7TT/zHdRNmMPnwV2vcOn45k2eVg
// SIG // Hq600j8J1zCBmDCBgKR+MHwxCzAJBgNVBAYTAlVTMRMw
// SIG // EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
// SIG // b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
// SIG // b24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1w
// SIG // IFBDQSAyMDEwAhMzAAAB0HcIqu+jF8bdAAEAAAHQMCIE
// SIG // IMDxYI3ComJrwFlmagM3LSITxSm88oYpLjTzfavkw9US
// SIG // MA0GCSqGSIb3DQEBCwUABIICAFcAVqG/CCKJffcCi5bg
// SIG // K3/M9yIsy9YwFVAeZU+N0/Z6oJvLulN9tqETzYHwSB5j
// SIG // 8rduKCxl7gnuj7+arNBGrdOnjj77iz5jVKhjFXUiR5J6
// SIG // VmesZzEq5lMyJqYvf4EhfivRV8QwqokXFrG3XsS28dHz
// SIG // UPr09y+B1hEA4BvcQNFr7z/UxmOFYh+qTd4M9RAW3z7B
// SIG // BgxU7gHyGDD0cGeUFFzNW/4thdjXmfcBnkEPCw5Klgfh
// SIG // zAVjsIFvBqgnCITfYCgtI+f0dMpUm7sNxbuVUhvss9K5
// SIG // LM6b1GuJ5/4t8SNU7YSOUMmy41IowKh55Fv5nxx9RRCu
// SIG // Wj1IhmLIufhq6ZoRKInPGuKTczCcEvHc4iA60CJt35LX
// SIG // OV3JehlKHOw8cpJygrsPCiyK6ML5+rZrjpcy+FusV+D9
// SIG // LMSKfBZYkP//+RuJm7TroTV4TsjumL9shjYY+stxzO3o
// SIG // Tc7YhzAXxgB3MiGecK5TFCin4F0LB33U3Ev/LA2m7fEr
// SIG // JbZZaJ6MuXDowmW9lcfTXoTAZfCG6FriozEmnsuU75ns
// SIG // TldmEixtKLeYTu4rt9ebq23vb7j2LqEPoNs/M6eL3lkB
// SIG // 1jrjUJtMMXc4WrfN57Y1n3x11RF82min+JTBvKLo9UE/
// SIG // VVq4EB4ymfMiZ4nMkaJWdeFzsRh0xLlXZVcvk9OrKj3l
// SIG // ClJ9
// SIG // End signature block
