version: "3.9"

services:
  @@containerName@@:
    image: "@@containerImage@@"
    restart: always
    ports: 
@@        - :[containerPorts]@@
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes: 
  postgresql_data: