#pragma once

using namespace ATL;

template <class T>
class CProxy_$interface_name$Events : public IConnectionPointImpl<T, &__uuidof(_$interface_name$Events), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
