define("detailsViewModel",["diagnosticsHub","diagnosticsHub-swimlanes","diagnosticsHub-ui","knockout","plugin-vs-v2"],((e,t,s,i,a)=>{return o={3864:e=>{const t=document.createElement("script");t.id="OpenDetailsButtonView",t.innerHTML=atob("PGRpdiBpZD0ib3BlbkRldGFpbHNCdXR0b24iIGNsYXNzPSJjb250YWluZXIiPg0KICAgIDxidXR0b24gY2xhc3M9Imh5cGVybGluay1idXR0b24gdG9vbGJhci1idXR0b24iIHJvbGU9ImxpbmsiIGRhdGEtYmluZD0iDQogICAgICAgIGxvY2FsaXplZFRleHQ6ICdCdXR0b25fT3BlbkRldGFpbHMnLA0KICAgICAgICBlbmFibGU6IGVuYWJsZWQsDQogICAgICAgIGNsaWNrOiBvbkNsaWNrLA0KICAgICAgICBvbkVudGVyOiBvbkNsaWNrLA0KICAgICAgICBjc3M6IHsgJ3Rvb2xiYXItYnV0dG9uLWRpc2FibGVkJzogIWVuYWJsZWQoKSB9Ij4NCiAgICA8L2J1dHRvbj4NCjwvZGl2Pg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},1289:e=>{const t=document.createElement("script");t.id="ActionLinkView",t.innerHTML=atob("PGRpdiBkYXRhLWJpbmQ9ImxvY2FsaXplZFRleHQ6IHN0YXR1c1RleHQiPjwvZGl2Pg0KPGEgcm9sZT0ibGluayIgdGFiaW5kZXg9IjAiDQogICAgZGF0YS1iaW5kPSJsb2NhbGl6ZWRUZXh0OiBsaW5rVGV4dCwNCiAgICAgICAgY2xpY2s6IGFjdGlvbiwNCiAgICAgICAgb25FbnRlcjogYWN0aW9uLA0KICAgICAgICBjc3M6IHsgJ2h5cGVybGluay1kaXNhYmxlZCc6IGFjdGlvblBlbmRpbmcgfSwNCiAgICAgICAgbG9jYWxpemVkQXJpYUxhYmVsOiBsaW5rVGV4dCI+DQo8L2E+"),t.type="text/html",document.head.appendChild(t),e.exports={}},3744:e=>{const t=document.createElement("script");t.id="MessageView",t.innerHTML=atob("PHNwYW4gdGFiSW5kZXg9IjAiIGRhdGEtYmluZD0iaHRtbDogJGRhdGEiPg0KPC9zcGFuPg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},9608:e=>{const t=document.createElement("script");t.id="OverlayView",t.innerHTML=atob("PGRpdiBpZD0ibWVzc2FnZS1vdmVybGF5IiBkYXRhLWJpbmQ9ImNzczogeyBoaWRlOiAhY3VycmVudE92ZXJsYXkoKSB9LCBpZjogY3VycmVudE92ZXJsYXkiPg0KICAgIDxkaXYgY2xhc3M9Im1lc3NhZ2UiIGRhdGEtYmluZD0idGVtcGxhdGU6IGN1cnJlbnRPdmVybGF5Ij4NCiAgICA8L2Rpdj4NCjwvZGl2Pg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},1787:e=>{const t=document.createElement("script");t.id="ProgressView",t.innerHTML=atob("PGRpdiBpZD0icHJvZ3Jlc3MtY29udHJvbCI+DQogICAgPHNwYW4gZGF0YS1iaW5kPSJ0ZXh0OiBzdGFnZU5hbWUiPjwvc3Bhbj4mbmJzcDs8c3BhbiBkYXRhLWJpbmQ9ImxvY2FsaXplZFRleHQ6ICdBZGRpdGlvbmFsT3V0cHV0SW5mbyciPjwvc3Bhbj4NCiAgICA8IS0tIGtvIHRlbXBsYXRlOiB7IG5hbWU6ICdJbmRldGVybWluYXRlUHJvZ3Jlc3MnIH0gLS0+PCEtLSAva28gLS0+DQogICAgPHByb2dyZXNzIGFyaWEtdmFsdWVtaW49IjAiIGRhdGEtYmluZD0iYXR0cjogeyBtYXg6IG1heFZhbHVlLA0KICAgICAgICAgICAgICB2YWx1ZTogY3VycmVudFZhbHVlLA0KICAgICAgICAgICAgICAnYXJpYS12YWx1ZW1heCc6IG1heFZhbHVlLA0KICAgICAgICAgICAgICAnYXJpYS12YWx1ZW5vdyc6IGN1cnJlbnRWYWx1ZX0sDQogICAgICAgICAgICAgIGxvY2FsaXplZEFyaWFMYWJlbDonT3ZlcmxheV9Qcm9ncmVzc0FyaWFMYWJlbCciPg0KICAgIDwvcHJvZ3Jlc3M+DQogICAgPGJ1dHRvbiBjbGFzcz0iaHlwZXJsaW5rLWJ1dHRvbiIgZGF0YS1iaW5kPSJsb2NhbGl6ZWRUZXh0OiAnQnV0dG9uX0NhbmNlbCcsIGNsaWNrOiBjYW5jZWwsIG9uRW50ZXI6IGNhbmNlbCI+PC9idXR0b24+DQo8L2Rpdj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},1131:e=>{const t=document.createElement("script");t.id="FilterContainerView",t.innerHTML=atob("PGRpdiBpZD0iZmlsdGVyQ29udGFpbmVyIiBjbGFzcz0idG9vbGJhci1idXR0b24iIGRhdGEtYmluZD0idGVtcGxhdGU6IHsgYWZ0ZXJSZW5kZXI6IG9uQWZ0ZXJEb21JbnNlcnQgfSwgZXZlbnQ6IHsga2V5ZG93bjogb25Fc2NLZXlEb3duIH0iPg0KICAgIDxidXR0b24gaWQ9InRocmVhZEhlYWRlciIgdGFiaW5kZXg9IjAiIGNsYXNzPSJ0b29sYmFyLWJ1dHRvbiIgYXJpYS1oYXNwb3B1cD0idHJ1ZSIgZGF0YS1iaW5kPSINCiAgICAgICAgICAgIGNzczogeyBub3REZWZhdWx0OiAhaXNEZWZhdWx0KCkgfSwNCiAgICAgICAgICAgIGNsaWNrOiB0b2dnbGVGbHlvdXQsDQogICAgICAgICAgICBldmVudDogeyBrZXlkb3duOiBvbkhlYWRlcktleURvd24gfSwNCiAgICAgICAgICAgIGRpc2FibGU6IGlzRGlzYWJsZWQsDQogICAgICAgICAgICBsb2NhbGl6ZWRUb29sdGlwOiAnSW5zdHJ1bWVudGF0aW9uVmlld0ZpbHRlclZpZXcnLA0KICAgICAgICAgICAgbG9jYWxpemVkQXJpYUxhYmVsOiAnSW5zdHJ1bWVudGF0aW9uVmlld0ZpbHRlclZpZXcnLA0KICAgICAgICAgICAgYXJpYUV4cGFuZGVkOiBmaWx0ZXJWaXNpYmxlIj4NCiAgICAgICAgPGRpdiBpZD0idGhyZWFkSGVhZGVySWNvbiIgY2xhc3M9Imljb24iIGRhdGEtYmluZD0ic3ZnSW1hZ2U6ICdkaWFnbm9zdGljc0h1Yi1maWx0ZXInIj48L2Rpdj4NCiAgICAgICAgPHNwYW4gY2xhc3M9ImRyb3Bkb3duLWJ1dHRvbiBidXR0b24tdGV4dCIgZGF0YS1iaW5kPSJsb2NhbGl6ZWRUZXh0OiAnSW5zdHJ1bWVudGF0aW9uVmlld0ZpbHRlclZpZXcnIj48L3NwYW4+DQogICAgPC9idXR0b24+DQogICAgPGRpdiBpZD0idGhyZWFkRmx5b3V0IiBkYXRhLWJpbmQ9ImNzczogeyBmbHlvdXRBY3RpdmU6IGZpbHRlclZpc2libGUoKSB9Ij4NCiAgICAgICAgPCEtLQ0KICAgICAgICA8ZGl2IGlkPSJqbWNWaWV3IiBjbGFzcz0iY29udGFpbmVyIiBkYXRhLWJpbmQ9Ig0KICAgICAgICBjc3M6IHsgaGFzRm9jdXM6IHNob3dKTUNIYXNGb2N1cygpIH0sDQogICAgICAgIGV2ZW50OiB7IGtleWRvd246IG9uRmlyc3RFbGVtZW50S2V5RG93biwgbW91c2VlbnRlcjogZnVuY3Rpb24odmlld01vZGVsKSB7IHZpZXdNb2RlbC5zaG93Sk1DSGFzRm9jdXModHJ1ZSk7IH0gfQ0KICAgICAgICAiPg0KICAgICAgICAgICAgPGlucHV0IGlkPSJqbWNTdGF0ZSIgdGFiaW5kZXg9IjAiIHR5cGU9ImNoZWNrYm94Ig0KICAgICAgICAgICAgICAgICAgIGRhdGEtYmluZD0iY2hlY2tlZDogc2hvd0ptYywgZm9jdXM6IHNob3dKTUNIYXNGb2N1cywNCiAgICAgICAgICAgICAgICAgICAgICAgIGxvY2FsaXplZEFyaWFMYWJlbDogJ0luc3RydW1lbnRhdGlvblZpZXdTaG93SnVzdE15Q29kZUxhYmVsJywNCiAgICAgICAgICAgICAgICAgICAgICAgIGF0dHI6IHsgJ2FyaWEtY2hlY2tlZCc6IHNob3dKbWMoKSB9IiAvPg0KICAgICAgICAgICAgPGxhYmVsIGNsYXNzPSJjaGVja2JveExhYmVsIGljb24iIGlkPSJqbWNJY29uIiBmb3I9ImptY1N0YXRlIiBkYXRhLWJpbmQ9InN2Z0ltYWdlOiAnZGlhZ25vc3RpY3NIdWItc2hvd0V4dGVybmFsQ29kZSciPjwvbGFiZWw+DQogICAgICAgICAgICA8bGFiZWwgY2xhc3M9ImNoZWNrYm94TGFiZWwiIGZvcj0iam1jU3RhdGUiIGRhdGEtYmluZD0ibG9jYWxpemVkVGV4dDogJ0luc3RydW1lbnRhdGlvblZpZXdTaG93SnVzdE15Q29kZUxhYmVsJyI+PC9sYWJlbD4NCiAgICAgICAgPC9kaXY+DQogICAgICAgIDxkaXYgaWQ9Im5hdGl2ZUZvbGRpbmdWaWV3IiBjbGFzcz0iY29udGFpbmVyIiBkYXRhLWJpbmQ9Ig0KICAgICAgICBjc3M6IHsgaGFzRm9jdXM6IHNob3dOYXRpdmVDb2RlSGFzRm9jdXNIYXNGb2N1cygpIH0sDQogICAgICAgIGV2ZW50OiB7IG1vdXNlZW50ZXI6IGZ1bmN0aW9uKHZpZXdNb2RlbCkgeyB2aWV3TW9kZWwuc2hvd05hdGl2ZUNvZGVIYXNGb2N1c0hhc0ZvY3VzKHRydWUpOyB9IH0NCiAgICAgICAgIj4NCiAgICAgICAgICAgIDxpbnB1dCBpZD0ibmF0aXZlRm9sZGluZ1N0YXRlIiB0YWJpbmRleD0iMCIgdHlwZT0iY2hlY2tib3giDQogICAgICAgICAgICAgICAgICAgZGF0YS1iaW5kPSJjaGVja2VkOiBzaG93TmF0aXZlQ29kZSwgZm9jdXM6IHNob3dOYXRpdmVDb2RlSGFzRm9jdXNIYXNGb2N1cywNCiAgICAgICAgICAgICAgICAgICAgICAgIGxvY2FsaXplZEFyaWFMYWJlbDogJ0luc3RydW1lbnRhdGlvblZpZXdTaG93TmF0aXZlQ29kZUxhYmVsJywNCiAgICAgICAgICAgICAgICAgICAgICAgIGF0dHI6IHsgJ2FyaWEtY2hlY2tlZCc6IHNob3dOYXRpdmVDb2RlKCkgfSIgLz4NCiAgICAgICAgICAgIDxsYWJlbCBjbGFzcz0iY2hlY2tib3hMYWJlbCBpY29uIiBpZD0ibmF0aXZlRm9sZGluZ0ljb24iIGZvcj0ibmF0aXZlRm9sZGluZ1N0YXRlIiBkYXRhLWJpbmQ9InN2Z0ltYWdlOiAnZGlhZ25vc3RpY3NIdWItc3RpdGNoQXN5bmNDb2RlJyI+PC9sYWJlbD4NCiAgICAgICAgICAgIDxsYWJlbCBjbGFzcz0iY2hlY2tib3hMYWJlbCIgZm9yPSJuYXRpdmVGb2xkaW5nU3RhdGUiIGRhdGEtYmluZD0ibG9jYWxpemVkVGV4dDogJ0luc3RydW1lbnRhdGlvblZpZXdTaG93TmF0aXZlQ29kZUxhYmVsJyI+PC9sYWJlbD4NCiAgICAgICAgPC9kaXY+DQogICAgICAgIC0tPg0KICAgICAgICA8ZGl2IGlkPSJzaG93VGhyZWFkc1ZpZXciIGNsYXNzPSJjb250YWluZXIiIGRhdGEtYmluZD0iDQogICAgICAgIGNzczogeyBoYXNGb2N1czogc2hvd1RocmVhZHNIYXNGb2N1cygpIH0sDQogICAgICAgIGV2ZW50OiB7IGtleWRvd246IG9uRmlyc3RFbGVtZW50S2V5RG93biwgbW91c2VlbnRlcjogZnVuY3Rpb24odmlld01vZGVsKSB7IHZpZXdNb2RlbC5zaG93VGhyZWFkc0hhc0ZvY3VzKHRydWUpOyB9IH0NCiAgICAgICAgIj4NCiAgICAgICAgICAgIDxpbnB1dCBpZD0ic2hvd1RocmVhZHMiIHRhYmluZGV4PSIwIiB0eXBlPSJjaGVja2JveCINCiAgICAgICAgICAgICAgICAgICBkYXRhLWJpbmQ9ImNoZWNrZWQ6IHNob3dUaHJlYWRzLCBmb2N1czogc2hvd1RocmVhZHNIYXNGb2N1cywNCiAgICAgICAgICAgICAgICAgICAgICAgIGxvY2FsaXplZEFyaWFMYWJlbDogJ0luc3RydW1lbnRhdGlvblZpZXdTaG93VGhyZWFkc0xhYmVsJywNCiAgICAgICAgICAgICAgICAgICAgICAgIGF0dHI6IHsgJ2FyaWEtY2hlY2tlZCc6IHNob3dUaHJlYWRzKCkgfSIgLz4NCiAgICAgICAgICAgIDxsYWJlbCBjbGFzcz0iY2hlY2tib3hMYWJlbCBpY29uIiBpZD0iam1jSWNvbiIgZm9yPSJqbWNTdGF0ZSIgZGF0YS1iaW5kPSJzdmdJbWFnZTogJ2RpYWdub3N0aWNzSHViLXNob3dFeHRlcm5hbENvZGUnIj48L2xhYmVsPg0KICAgICAgICAgICAgPGxhYmVsIGNsYXNzPSJjaGVja2JveExhYmVsIiBmb3I9InNob3dUaHJlYWRzIiBkYXRhLWJpbmQ9ImxvY2FsaXplZFRleHQ6ICdJbnN0cnVtZW50YXRpb25WaWV3U2hvd1RocmVhZHNMYWJlbCciPjwvbGFiZWw+DQogICAgICAgIDwvZGl2Pg0KICAgICAgICA8c3BhbiBpZD0idGhyZWFkRmlsdGVySGVhZGVyIiBkYXRhLWJpbmQ9ImxvY2FsaXplZFRleHQ6ICdJbnN0cnVtZW50YXRpb25WaWV3VGhyZWFkTGlzdGJveExhYmVsJyI+PC9zcGFuPg0KICAgICAgICA8dWwgaWQ9InRocmVhZEZpbHRlckxpc3QiIHRhYmluZGV4PSIwIiBkYXRhLWJpbmQ9Ig0KICAgICAgICAgICAgZXZlbnQ6IHsga2V5ZG93bjogb25LZXlEb3duLCBmb2N1czogb25Gb2N1cyB9LA0KICAgICAgICAgICAgbG9jYWxpemVkQXJpYUxhYmVsOiAnSW5zdHJ1bWVudGF0aW9uVmlld1RocmVhZExpc3Rib3hMYWJlbCciPg0KICAgICAgICAgICAgPGxpIGRhdGEtYmluZD0iDQogICAgICAgICAgICAgICAgY3NzOiB7IGhhc0ZvY3VzOiBzZWxlY3RBbGxIYXNGb2N1cygpIH0sDQogICAgICAgICAgICAgICAgZXZlbnQ6IHsgbW91c2VlbnRlcjogZnVuY3Rpb24odmlld01vZGVsKSB7IHZpZXdNb2RlbC5zZWxlY3RBbGxIYXNGb2N1cyh0cnVlKTsgfSB9DQogICAgICAgICAgICAgICAgIj4NCiAgICAgICAgICAgICAgICA8bGFiZWwgY2xhc3M9ImNvbnRhaW5lciI+DQogICAgICAgICAgICAgICAgICAgIDxpbnB1dCB0eXBlPSJjaGVja2JveCIgdGFiaW5kZXg9Ii0xIiBkYXRhLWJpbmQ9ImNoZWNrZWQ6IHNlbGVjdEFsbCwgZm9jdXM6IHNlbGVjdEFsbEhhc0ZvY3VzLA0KICAgICAgICAgICAgICAgICAgICAgICAgbG9jYWxpemVkQXJpYUxhYmVsOiAnSW5zdHJ1bWVudGF0aW9uVmlld1NlbGVjdEFsbCcsDQogICAgICAgICAgICAgICAgICAgICAgICBhdHRyOiB7ICdhcmlhLWNoZWNrZWQnOiBzZWxlY3RBbGwoKSB9IiAvPg0KICAgICAgICAgICAgICAgICAgICA8c3BhbiBjbGFzcz0iY2hlY2tib3hMYWJlbCIgZGF0YS1iaW5kPSJsb2NhbGl6ZWRUZXh0OiAnSW5zdHJ1bWVudGF0aW9uVmlld1NlbGVjdEFsbCciPjwvc3Bhbj4NCiAgICAgICAgICAgICAgICA8L2xhYmVsPg0KICAgICAgICAgICAgPC9saT4NCiAgICAgICAgICAgIDwhLS0ga28gZm9yZWFjaDogdGhyZWFkcyAtLT4NCiAgICAgICAgICAgIDxsaSBkYXRhLWJpbmQ9Ig0KICAgICAgICAgICAgICAgICAgICBjc3M6IHsgaGFzRm9jdXM6IGhhc0ZvY3VzKCkgfSwNCiAgICAgICAgICAgICAgICAgICAgZXZlbnQ6IHsgbW91c2VlbnRlcjogZnVuY3Rpb24odmlld01vZGVsKSB7IHZpZXdNb2RlbC5oYXNGb2N1cyh0cnVlKTsgfSB9LA0KICAgICAgICAgICAgICAgICAgICB0b29sdGlwOiB0b29sdGlwIj4NCiAgICAgICAgICAgICAgICA8IS0tIEFib3ZlIHdlIHVzZSBKU09OLnN0cmluZ2lmeSBpbiB0aGUgbXVsdGlsaW5lIHRvb2x0aXAgYXMgRGF5dG9uYSB3b24ndCBpbmNsdWRlIGxpbmUgYnJlYWtzIHdpdGgganVzdCBhIHN0cmluZyAtLT4NCiAgICAgICAgICAgICAgICA8bGFiZWwgY2xhc3M9ImNvbnRhaW5lciI+DQogICAgICAgICAgICAgICAgICAgIDxpbnB1dCB0eXBlPSJjaGVja2JveCIgdGFiaW5kZXg9Ii0xIiBkYXRhLWJpbmQ9ImNoZWNrZWQ6IGlzQ2hlY2tlZCwgZm9jdXM6IGhhc0ZvY3VzLCBhdHRyOiB7DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgJ2FyaWEtbGFiZWwnOiBsYWJlbCgpLA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICdhcmlhLWNoZWNrZWQnOiBpc0NoZWNrZWQoKQ0KICAgICAgICAgICAgICAgICAgICAgICAgfSIgLz4NCiAgICAgICAgICAgICAgICAgICAgPHNwYW4gY2xhc3M9ImNoZWNrYm94TGFiZWwiIGRhdGEtYmluZD0idGV4dDogbGFiZWwiPjwvc3Bhbj4NCiAgICAgICAgICAgICAgICA8L2xhYmVsPg0KICAgICAgICAgICAgPC9saT4NCiAgICAgICAgICAgIDwhLS0gL2tvIC0tPg0KICAgICAgICA8L3VsPg0KICAgICAgICA8ZGl2IGlkPSJ0aHJlYWRGaWx0ZXJGb290ZXIiPg0KICAgICAgICAgICAgPGJ1dHRvbiBpZD0idGhyZWFkRmlsdGVyQ29tbWl0IiBkYXRhLWJpbmQ9Ig0KICAgICAgICAgICAgICAgIGNsaWNrOiBjb21taXRDaGFuZ2VzLA0KICAgICAgICAgICAgICAgIGxvY2FsaXplZEFyaWFMYWJlbDogJ0J1dHRvbl9JbnN0cnVtZW50YXRpb25WaWV3QXBwbHknLA0KICAgICAgICAgICAgICAgIGVuYWJsZTogYXBwbHlCdXR0b25TdGF0dXMiPg0KICAgICAgICAgICAgICAgIDwhLS0gVGhpcyBzZW1hbnRpY2FsbHkgbWVhbmluZ2xlc3Mgc3BhbiBpcyBoZXJlIHNvIHdlIGNhbiByZXNldCBJRSdzIGRlZmF1bHQgY2xpY2sgImFuaW1hdGlvbiIgLS0+DQogICAgICAgICAgICAgICAgPHNwYW4gZGF0YS1iaW5kPSJsb2NhbGl6ZWRUZXh0OiAnQnV0dG9uX0luc3RydW1lbnRhdGlvblZpZXdBcHBseSciPjwvc3Bhbj4NCiAgICAgICAgICAgIDwvYnV0dG9uPg0KICAgICAgICAgICAgPGJ1dHRvbiBpZD0idGhyZWFkRmlsdGVyUm9sbGJhY2siIGRhdGEtYmluZD0iDQogICAgICAgICAgICAgICAgY2xpY2s6IHJvbGxiYWNrQ2hhbmdlcywNCiAgICAgICAgICAgICAgICBldmVudDogeyBrZXlkb3duOiBvbkNhbmNlbEtleURvd24gfSwNCiAgICAgICAgICAgICAgICBmb2N1czogY2FuY2VsSGFzRm9jdXMsDQogICAgICAgICAgICAgICAgbG9jYWxpemVkQXJpYUxhYmVsOiAnQnV0dG9uX0luc3RydW1lbnRhdGlvblZpZXdDYW5jZWwnIj4NCiAgICAgICAgICAgICAgICA8IS0tIFRoaXMgc2VtYW50aWNhbGx5IG1lYW5pbmdsZXNzIHNwYW4gaXMgaGVyZSBzbyB3ZSBjYW4gcmVzZXQgSUUncyBkZWZhdWx0IGNsaWNrICJhbmltYXRpb24iIC0tPg0KICAgICAgICAgICAgICAgIDxzcGFuIGRhdGEtYmluZD0ibG9jYWxpemVkVGV4dDogJ0J1dHRvbl9JbnN0cnVtZW50YXRpb25WaWV3Q2FuY2VsJyI+PC9zcGFuPg0KICAgICAgICAgICAgPC9idXR0b24+DQogICAgICAgIDwvZGl2Pg0KICAgIDwvZGl2Pg0KPC9kaXY+"),t.type="text/html",document.head.appendChild(t),e.exports={}},4103:e=>{const t=document.createElement("script");t.id="IndeterminateProgress",t.innerHTML=atob("PGRpdiBjbGFzcz0ic3Bpbm5lciIgcm9sZT0icHJvZ3Jlc3NiYXIiIGFyaWEtdmFsdWVub3c9IjAiIGFyaWEtdmFsdWVtaW49IjAiIGFyaWEtdmFsdWVtYXg9IjEwMCIgYXJpYS1saXZlPSJhc3NlcnRpdmUiDQogICAgIGRhdGEtYmluZD0ibG9jYWxpemVkQXJpYUxhYmVsOidPdmVybGF5X1Byb2dyZXNzSW5kZXRlcm1pbmF0ZUFyaWFMYWJlbCciPg0KICAgIDxkaXYgY2xhc3M9ImJhcjEiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjIiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjMiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjQiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjUiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjYiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjciPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjgiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjkiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjEwIj48L2Rpdj4NCjwvZGl2Pg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},5760:(e,t,s)=>{var i,a;i=[s,t,s(3028),s(909),s(8649),s(3864)],a=function(e,t,s,i,a){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.OpenDetailsButtonViewModel=void 0,t.OpenDetailsButtonViewModel=class{constructor(){this._instrumentationToolMarshaler=new i.InstrumentationToolPortMarshaler,this._telemetryInstrumentation=new a.InstrumentationToolTelemetryPortMarshaler,this._enabled=s.observable(!0)}get enabled(){return this._enabled}onClick(e,t){return!this._enabled()||(this._telemetryInstrumentation.openDetails(),this._instrumentationToolMarshaler.showSplitViewToolWindow(),!1)}}}.apply(t,i),void 0===a||(e.exports=a)},952:(e,t,s)=>{var i;i=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.flameGraphViewModelMappingKey=t.flatFunctionsViewModelMappingKey=t.modulesViewModelMappingKey=t.callTreeViewModelMappingKey=t.callerCalleeViewModelMappingKey=t.functionLimit=t.errorNameCanceled=t.collectionDetailsViewId=t.analysisDetailsViewId=t.instrumentationAnalyzer=void 0,t.instrumentationAnalyzer=function(){return"DCA8B3EF-28C5-4B08-BAFC-B072F8AA9277"},t.analysisDetailsViewId=function(){return"294b1998-6add-4b6f-9210-730ac15a772b"},t.collectionDetailsViewId=function(){return"fda7c8a5-71ee-421b-a1ad-f5b00a355af1"},t.errorNameCanceled=function(){return"Canceled"},t.functionLimit=function(){return 5},t.callerCalleeViewModelMappingKey=function(){return"CallerCalleeView"},t.callTreeViewModelMappingKey=function(){return"CallTreeView"},t.modulesViewModelMappingKey=function(){return"ModulesView"},t.flatFunctionsViewModelMappingKey=function(){return"FlatFunctionsView"},t.flameGraphViewModelMappingKey=function(){return"FlameGraphView"}}.apply(t,[s,t]),void 0===i||(e.exports=i)},8017:function(e,t,s){var i,a,o=this&&this.__createBinding||(Object.create?function(e,t,s,i){void 0===i&&(i=s),Object.defineProperty(e,i,{enumerable:!0,get:function(){return t[s]}})}:function(e,t,s,i){void 0===i&&(i=s),e[i]=t[s]}),n=this&&this.__exportStar||function(e,t){for(var s in e)"default"===s||Object.prototype.hasOwnProperty.call(t,s)||o(t,e,s)};i=[s,t,s(5226),s(3028),s(5639),s(4881),s(909),s(8649),s(1654),s(7886),s(9089),s(5760),s(952),s(8117),s(8117),s(4881),s(8558),s(5253),s(4881),s(8117),s(2560),s(8117),s(3744),s(9608),s(1289),s(4103)],a=function(e,t,s,i,a,o,l,r,d,h,g,u,c,I,C,m,A,p,b,v,S,G){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.getDetailsViewModel=t.DetailsViewModel=void 0,n(a,t);class w{constructor(){this._instrumentationToolMarshaler=new l.InstrumentationToolPortMarshaler,this._telemetryInstrumentation=new r.InstrumentationToolTelemetryPortMarshaler,this._progressViewModel=new g.ProgressViewModel(s.Resources.getString("PreparingInstrumentationDataProgressTaskName"),100),this._resultStatus=i.observable(null),this._currentOverlay=i.pureComputed((()=>this.computeOverlay())),this._isVisible=!0,this._viewId=c.analysisDetailsViewId(),this._agentErrorMessage=i.observable(""),this._resultId=i.observable(null),this._topFunctionsDataLoadPromise=null,this._topFunctionDataLoadStatus=i.observable(o.DataLoadEvent.DataLoadCompleted),this._hotPathDataLoadPromise=null,this._topInsightsDataLoadPromise=null,this._canShowTopInsights=!1,this._classFrequencyDataLoadPromise=null,this.decimals=2,this._msecUnitConverter=new S.MillisecondTimeUnitConverter(this.decimals),this._logger=G.getLogger("InstrumentationDetailsViewModel"),this.prevCompleteResult=null}get collectedClasses(){return this._collectedClasses}get topFunctions(){return this._topFunctions}get hotPath(){return this._hotPath}get topInsights(){return this._topInsights}get threadFilterViewModel(){return this._threadFilterViewModel}get openDetailsButtonViewModel(){return this._openDetailsButtonViewModel}get currentOverlay(){return this._currentOverlay}get msec(){return this._msecUnitConverter}get topFunctionDataLoadPromise(){return this._topFunctionsDataLoadPromise?this._topFunctionsDataLoadPromise:this.computeTopFunctions()}get topFunctionDataLoadStatus(){return this._topFunctionDataLoadStatus}get marshaler(){return this._instrumentationToolMarshaler}navigate(e,t,s){return this.navigateAsync(e,t),!1}async navigateAsync(e,t){const s=new l.InstrumentationToolPortMarshaler,i=new r.InstrumentationToolTelemetryPortMarshaler;let a=null,o=!1;switch(e){case"TopFunctions":i.topFunctionLink(),a=h.InstrumentationToolView.FlatFunctionsView;break;case"HotPath":i.hotPathLink(),a=h.InstrumentationToolView.CallTreeView,o=!0;break;case"TopInsights":i.topInsightsLink(t.ruleId,t.ruleType),a=h.InstrumentationToolView.CallTreeView}await s.raiseContextChangedEvent({context:{rowId:t.id,rowType:t.rowType,viewToShow:a,showHotPath:o}}).then((()=>{s.showSplitViewToolWindow()}))}linkNavigate(e,t,s){return this._telemetryInstrumentation.topInsightsLinkClicked(e,t.ruleId,t.ruleType),this._instrumentationToolMarshaler.openLink(e),!1}requestHelp(e,t){return this._telemetryInstrumentation.topInsightsCopilotLinkClicked(e.ruleId,e.ruleType),this.requestHelpAsync(e),!1}async requestHelpAsync(e){await this.navigateAsync("TopInsights",e);const t=this._dataWarehouse.getResultById(this._resultId());await t.getResult({view:"dashboard-view",type:h.ResultTaskType.InsightHelp,ruleId:e.ruleId},this._topInsightsDataLoadCancellationTokenSource.token)}async initialize(){this._canShowTopInsights=await this._instrumentationToolMarshaler.isTopInsightsSupported();const e=await this._instrumentationToolMarshaler.getCurrentResultStatus();this._resultStatus(e),await this.initializeResultInformation();const t=I.getViewEventManager();t.detailsViewSelectionChanged.addEventListener(this.onDetailsViewSelectionChangedEvent.bind(this)),i.applyBindings(this),t.detailsViewReady.raiseEvent({Id:this._viewId})}get canShowTopInsights(){return this._canShowTopInsights}initializeResultInformation(){return C.loadDataWarehouse().then((e=>{this._dataWarehouse=e,this._threadFilterViewModel=new d.ThreadFilterViewModel(e),this._openDetailsButtonViewModel=new u.OpenDetailsButtonViewModel,this._collectedClasses=m.AsyncComputed((()=>this.computeCollectedClasses())),this._topFunctions=m.AsyncComputed((()=>this.computeTopFunctions())),this._hotPath=m.AsyncComputed((()=>this.computeHotPath())),this._topInsights=m.AsyncComputed((()=>this.computeTopInsights())),this._resultStatus.subscribe((e=>this.onResultStatusChanged(e))),this._instrumentationToolMarshaler.resultStatusUpdatedEvent.addEventListener((e=>this._resultStatus(e.currentResultStatus))),this._instrumentationToolMarshaler.requestResultUpdate(),this._progressViewModel.cancellationRequestedEvent.addEventListener((()=>{this._instrumentationToolMarshaler.cancelResult(),this._threadFilterViewModel.cancelLoading()}))}))}onResultStatusChanged(e){if(null!==this.prevCompleteResult&&this.prevCompleteResult.eventId>e.eventId)return this._logger.info(`Previous complete ResultStatusUpdated event has ID ${this.prevCompleteResult.eventId}, event with ID ${e.eventId} out of order, updating result status with previous complete result status`),void this._resultStatus(this.prevCompleteResult);this._isVisible&&e.preparationStatus===h.ResultPreparationStatus.InProgress&&this._progressViewModel.currentValue(e.completionPercentage),e.result.stage===h.ResultStage.Threads&&e.result.status===h.ResultPreparationStatus.Completed&&(this.prevCompleteResult=e,this._threadFilterViewModel.resultId(e.result.resultId)),e.result.stage===h.ResultStage.Model&&e.result.status===h.ResultPreparationStatus.Completed&&(this.prevCompleteResult=e,this._resultId(this._resultStatus().result.resultId))}onDetailsViewSelectionChangedEvent(e){this._isVisible=e.Id.toUpperCase()===this._viewId.toUpperCase(),this._isVisible&&(this._resultStatus().preparationStatus===h.ResultPreparationStatus.InProgress?this._progressViewModel.currentValue(this._resultStatus().completionPercentage):(this._resultStatus().preparationStatus,h.ResultPreparationStatus.Completed))}computeOverlay(){if(this._agentErrorMessage())return{name:"MessageView",data:this._agentErrorMessage()};const e=this._resultStatus();return e.preparationStatus===h.ResultPreparationStatus.InProgress?{name:"ProgressView",data:this._progressViewModel}:this._threadFilterViewModel.dataLoadStatus()===o.DataLoadEvent.DataLoadCanceled?{name:"MessageView",data:s.Resources.getString("Overlay_OperationIncomplete")}:this._threadFilterViewModel.dataLoadStatus()===o.DataLoadEvent.DataLoadFailed?{name:"MessageView",data:s.Resources.getString("Overlay_UnableShowData")}:this._threadFilterViewModel.dataLoadStatus()===o.DataLoadEvent.DataLoadCompleted&&this.topFunctions()&&0===this._topFunctions().length?{name:"MessageView",data:s.Resources.getString("Overlay_NoData")}:e.message?{name:"MessageView",data:e.message}:null}computeCollectedClasses(){if("number"!=typeof this._resultId())return Promise.resolve([]);this._classFrequencyLoadCancellationTokenSource&&this._classFrequencyLoadCancellationTokenSource.cancel(),this._classFrequencyLoadCancellationTokenSource=new v.CancellationTokenSource;const e=this._dataWarehouse.getResultById(this._resultId());return this._classFrequencyDataLoadPromise=e.getResult({view:"dashboard-view",type:h.ResultTaskType.ClassFrequency},this._classFrequencyLoadCancellationTokenSource.token).then((e=>{const t=[];for(const s in e){if("0"===s)continue;const i={className:s,timeInCategory:e[s],percentTimeInCategory:e[s]/e[0]};t.push(i)}const i=t.reduce(((e,t)=>e+t.timeInCategory),0);return t.filter((e=>e.timeInCategory)).sort(((e,t)=>t.timeInCategory-e.timeInCategory)).slice(0,5).map((e=>{const t=e.timeInCategory/i,a=A.localizeNumber(t,{style:"percent",minimumFractionDigits:1});return{value:e.timeInCategory,label:s.Resources.getString("ClassSelection",e.className,a)}}))})),this._classFrequencyDataLoadPromise}computeTopFunctions(){if("number"!=typeof this._resultId())return Promise.resolve(null);this._topFunctionsDataLoadCancellationTokenSource&&this._topFunctionsDataLoadCancellationTokenSource.cancel(),this._topFunctionsDataLoadCancellationTokenSource=new v.CancellationTokenSource,this._topFunctionsDataLoadCancellationTokenSource.token.onCancellationRequested.addEventListener((()=>{this._topFunctionDataLoadStatus(o.DataLoadEvent.DataLoadCanceled)}),{once:!0});const e=this._dataWarehouse.getResultById(this._resultId());return this._topFunctionDataLoadStatus(o.DataLoadEvent.DataLoadStart),this._topFunctionsDataLoadPromise=e.getResult({view:"dashboard-view",type:h.ResultTaskType.TopFunctions,functionLimit:5},this._topFunctionsDataLoadCancellationTokenSource.token).then((e=>this.labelRows(e))).then((e=>(this._topFunctionDataLoadStatus(o.DataLoadEvent.DataLoadCompleted),e)),(e=>(e.name!==c.errorNameCanceled()&&this._topFunctionDataLoadStatus(o.DataLoadEvent.DataLoadFailed),[]))),this._topFunctionsDataLoadPromise}computeHotPath(){if("number"!=typeof this._resultId())return Promise.resolve(null);this._hotPathDataLoadCancellationTokenSource&&this._hotPathDataLoadCancellationTokenSource.cancel(),this._hotPathDataLoadCancellationTokenSource=new v.CancellationTokenSource;const e=this._dataWarehouse.getResultById(this._resultId());return this._hotPathDataLoadPromise=e.getResult({view:"dashboard-view",type:h.ResultTaskType.ExpandHotPath},this._hotPathDataLoadCancellationTokenSource.token).then((e=>{let t=0;for(const s of e)s.depth=t,s.isHotItem||++t;return e})).then((e=>this.labelRows(e))).then((e=>(this._hotPathDataLoadPromise=null,e)),(e=>(this._hotPathDataLoadPromise=null,[]))),this._hotPathDataLoadPromise}computeTopInsights(){if(!this._canShowTopInsights)return Promise.resolve(null);this._topInsightsDataLoadCancellationTokenSource&&this._topInsightsDataLoadCancellationTokenSource.cancel(),this._topInsightsDataLoadCancellationTokenSource=new v.CancellationTokenSource;const e=this._dataWarehouse.getResultById(this._resultId());return this._topInsightsDataLoadPromise=e.getResult({view:"dashboard-view",type:h.ResultTaskType.TopInsights},this._topInsightsDataLoadCancellationTokenSource.token).then((e=>e)),this._topInsightsDataLoadPromise.then((()=>{this._topInsightsDataLoadPromise=null}),(e=>{this._topInsightsDataLoadPromise=null})),this._topInsightsDataLoadPromise}labelRows(e){return this._dataWarehouse.getJmcService().getJmcEnabledState().then((t=>(e.forEach((e=>{if(e.aggType!==o.AggregateType.BrokenStack){if(!t)return e.aggType===o.AggregateType.AsyncMethod?void(e.label=s.Resources.getString("AsyncMethodLabel")):e.aggType===o.AggregateType.Native?void(e.label=s.Resources.getString("NativeCodeLabel")):void(e.label="");if(e.name)switch(e.jmcState){case o.JmcState.SystemCode:return void(e.label=s.Resources.getString("SystemCallLabel"));case o.JmcState.LibraryCode:return void(e.label=s.Resources.getString("ExternalCallLabel"))}switch(e.aggType){case o.AggregateType.SystemCode:return void(e.label=s.Resources.getString("SystemCodeLabel"));case o.AggregateType.JmcRejected:return void(e.label=s.Resources.getString("ExternalCodeLabel"));case o.AggregateType.AsyncMethod:return void(e.label=s.Resources.getString("AsyncMethodLabel"));case o.AggregateType.Native:return void(e.label=s.Resources.getString("NativeCodeLabel"));default:return void(e.label="")}}else e.label=s.Resources.getString("UnwalkableStackLabel")})),e)))}}let _;t.DetailsViewModel=w,(new p.UtilitiesPortMarshaler).getDoubleClickTimeMs().then((async e=>{b.Init(e),_=new w,await _.initialize()})),t.getDetailsViewModel=function(){return _}}.apply(t,i),void 0===a||(e.exports=a)},5639:(e,t,s)=>{var i,a;i=[s,t,s(8558)],a=function(e,t,s){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),window.InstrumentationUI_onAfterDomInsert=s.onAfterDomInsert}.apply(t,i),void 0===a||(e.exports=a)},909:(e,t,s)=>{var i,a;i=[s,t,s(5226),s(8117)],a=function(e,t,s,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.InstrumentationToolPortMarshaler=void 0;let a=null;t.InstrumentationToolPortMarshaler=class{constructor(){null===a&&(a=s.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.Instrumentation.InstrumentationToolMarshaler",{},!0)),this._contextChangedEvent=new i.ObservableEvent(a,"InstrumentationTool.ContextChangedEvent"),this._resultStatusUpdatedEvent=new i.ObservableEvent(a,"InstrumentationTool.ResultStatusUpdatedEvent"),this._detailsViewChangedEvent=new i.ObservableEvent(a,"InstrumentationTool.DetailsViewChanged")}get contextChangedEvent(){return this._contextChangedEvent}get resultStatusUpdatedEvent(){return this._resultStatusUpdatedEvent}get detailsViewChangedEvent(){return this._detailsViewChangedEvent}getCurrentContext(){return a._call("getCurrentContext")}getCurrentResultStatus(){return a._call("getCurrentResultStatus")}raiseContextChangedEvent(e){return a._call("raiseContextChangedEvent",e)}raiseDetailsViewChangedEvent(e){return a._call("raiseDetailsViewChangedEvent",e)}setThreadSelection(e){return a._call("setThreadSelection",e)}requestResultUpdate(){return a._call("requestResultUpdate")}cancelResult(){return a._call("cancelResult")}getColumnSetting(e){return a._call("getColumnSetting",e)}onColumnChanged(e,t){return a._call("onColumnChanged",e,t)}showSplitViewToolWindow(){return a._call("showSplitViewToolWindow")}isShowThreadsEnabled(){return a._call("isShowThreadsEnabled")}isNativeCodeFoldingEnabled(){return a._call("isNativeCodeFoldingEnabled")}isTopInsightsSupported(){return a._call("isTopInsightsSupported")}isNativeCodeFoldingPersisted(){return a._call("isNativeCodeFoldingPersisted")}setShowThreadsEnabled(e){return a._call("setShowThreads",e)}setNativeCodeFoldingEnabled(e){return a._call("setNativeCodeFolding",e)}loadModuleSymbols(e){return a._call("loadModuleSymbols",e)}loadAllSymbols(){return a._call("loadAllSymbols")}openLink(e){return a._call("openLink",e)}}}.apply(t,i),void 0===a||(e.exports=a)},8649:(e,t,s)=>{var i,a;i=[s,t,s(5226)],a=function(e,t,s){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.InstrumentationToolTelemetryPortMarshaler=void 0;let i=null;t.InstrumentationToolTelemetryPortMarshaler=class{constructor(){null===i&&(i=s.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.Instrumentation.VisualStudio.InstrumentationToolTelemetryMarshaler",{},!0))}hotPathUsed(){i._post("hotPathUsed")}filterViewOpen(){i._post("filterViewOpen")}viewOpened(e){i._post("viewOpened",e)}openDetails(){i._post("openDetails")}topFunctionLink(){i._post("topFunctionLink")}hotPathLink(){i._post("hotPathLink")}searchIsUsed(){i._post("searchIsUsed")}searchOptionsChanged(){i._post("searchOptionsChanged")}topInsightsLink(e,t){i._post("topInsightsLink",e,t)}topInsightsLinkClicked(e,t,s){i._post("topInsightsLinkClicked",e,t,s)}topInsightsCopilotLinkClicked(e,t){i._post("topInsightsCopilotClicked",e,t)}crossReferenceUsed(){i._post("crossReferenceUsed")}enabledToggle(e){i._post("enabledToggle",e)}}}.apply(t,i),void 0===a||(e.exports=a)},7886:(e,t,s)=>{var i;i=function(e,t){"use strict";var s,i,a,o,n,l,r;Object.defineProperty(t,"__esModule",{value:!0}),t.SortColumn=t.InstrumentationToolView=t.ResultStage=t.ResultNotStartedReason=t.ResultPreparationStatus=t.ActivityType=t.ResultTaskType=void 0,(r=t.ResultTaskType||(t.ResultTaskType={}))[r.Expand=1]="Expand",r[r.Search=2]="Search",r[r.GetData=3]="GetData",r[r.Sort=4]="Sort",r[r.ExpandHotPath=5]="ExpandHotPath",r[r.TopFunctions=6]="TopFunctions",r[r.GetNodePath=7]="GetNodePath",r[r.Autocomplete=9]="Autocomplete",r[r.ClassFrequency=10]="ClassFrequency",r[r.TopInsights=11]="TopInsights",r[r.InsightHelp=12]="InsightHelp",(l=t.ActivityType||(t.ActivityType={}))[l.Unknown=0]="Unknown",l[l.ThreadRun=1]="ThreadRun",l[l.AsyncTask=2]="AsyncTask",(n=t.ResultPreparationStatus||(t.ResultPreparationStatus={}))[n.NotStarted=0]="NotStarted",n[n.InProgress=1]="InProgress",n[n.Completed=2]="Completed",n[n.Canceled=3]="Canceled",n[n.Failed=4]="Failed",(o=t.ResultNotStartedReason||(t.ResultNotStartedReason={}))[o.Unknown=0]="Unknown",o[o.NoValidTimeSelection=1]="NoValidTimeSelection",o[o.NoValidThreadSelection=2]="NoValidThreadSelection",o[o.ToolIsDisabled=3]="ToolIsDisabled",o[o.TargetRunningUnderDebugger=4]="TargetRunningUnderDebugger",(a=t.ResultStage||(t.ResultStage={}))[a.Unknown=0]="Unknown",a[a.Threads=1]="Threads",a[a.Model=2]="Model",(i=t.InstrumentationToolView||(t.InstrumentationToolView={}))[i.FlatFunctionsView=1]="FlatFunctionsView",i[i.CallerCalleeView=2]="CallerCalleeView",i[i.CallTreeView=3]="CallTreeView",i[i.ModulesView=4]="ModulesView",i[i.FlameGraphView=5]="FlameGraphView",(s=t.SortColumn||(t.SortColumn={}))[s.Id=1]="Id",s[s.FunctionName=2]="FunctionName",s[s.TotalMetrics=3]="TotalMetrics",s[s.SelfMetrics=4]="SelfMetrics",s[s.ModuleName=5]="ModuleName",s[s.CategoryName=6]="CategoryName",s[s.CallCount=7]="CallCount",s[s.MaxTotal=8]="MaxTotal",s[s.MaxSelf=9]="MaxSelf",s[s.MinTotal=10]="MinTotal",s[s.MinSelf=11]="MinSelf",s[s.AvgTotal=12]="AvgTotal",s[s.AvgSelf=13]="AvgSelf"}.apply(t,[s,t]),void 0===i||(e.exports=i)},9089:(e,t,s)=>{var i,a;i=[s,t,s(3028),s(8117),s(1787)],a=function(e,t,s,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.ProgressViewModel=void 0,t.ProgressViewModel=class{constructor(e,t){this._cancellationRequestedEvent=new i.AggregatedEvent,this._currentValue=s.observable(0),this._stageName=e,this._maxValue=t}get stageName(){return this._stageName}get maxValue(){return this._maxValue}get currentValue(){return this._currentValue}get cancellationRequestedEvent(){return this._cancellationRequestedEvent}cancel(){this._cancellationRequestedEvent.invokeEvent(null)}}}.apply(t,i),void 0===a||(e.exports=a)},1654:(e,t,s)=>{var i,a;i=[s,t,s(3028),s(909),s(9293),s(8117),s(4881),s(8117),s(8117),s(2560),s(2560),s(952),s(2560),s(8117),s(1131)],a=function(e,t,s,i,a,o,n,l,r,d,h,g,u,c){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.ThreadFilterViewModel=void 0,t.ThreadFilterViewModel=class{constructor(e){this._isDefault=s.observable(!0),this._threads=s.observableArray([]),this._isDisabled=s.observable(!1),this._threadDomain=s.observableArray([]),this._selectAll=s.observable(!0),this._selectAllHasFocus=s.observable(!1),this._cancelHasFocus=s.observable(!1),this._showJmc=s.observable(!0),this._showThreads=s.observable(!1),this._showNativeCode=s.observable(!0),this._showJMCHasFocus=s.observable(!1),this._showThreadsHasFocus=s.observable(!1),this._showNativeCodeHasFocus=s.observable(!1),this._filterVisible=s.observable(!1),this._instrumentationToolMarshaler=new i.InstrumentationToolPortMarshaler,this._dataLoadStatus=s.observable(n.DataLoadEvent.DataLoadCompleted),this._committedShowThreads=!1,this._committedShowJMC=!0,this._committedShowNativeCode=!0,this._resultId=s.observable(null),this._onJmcChangedBoundFunction=e=>this.onJmcChanged(e),this._currentFocusedIndex=null,this._selectAllSubscription=this.selectAll.subscribe(this.onSelectAll.bind(this)),this._dataWarehouse=e,this._viewEventManager=l.getViewEventManager(),this._viewEventManager.jmcEnabledStateChanged.addEventListener(this._onJmcChangedBoundFunction),this._applyButtonStatus=s.computed((()=>!!this.threads&&this.threads().some((e=>e.isChecked())))),this._isDisabled.subscribe((e=>{e&&(this.rollbackChanges(),this.filterVisible(!1))})),this._resultId.subscribe((e=>this.onResultChanged(e))),this._setupPromise=this._instrumentationToolMarshaler.isNativeCodeFoldingEnabled().then((e=>(this.showNativeCode(!e),this._committedShowNativeCode=this.showNativeCode(),this._instrumentationToolMarshaler.setNativeCodeFoldingEnabled({currentNativeCodeFolding:e,shouldReanalyze:!1})))).then((()=>{this._dataWarehouse.getJmcService().getJmcEnabledState().then((e=>{this.onJmcChanged({currEnabledState:e,prevEnabledState:this._committedShowJMC})}))})).then((()=>{this._instrumentationToolMarshaler.isShowThreadsEnabled().then((e=>(this.showThreads(e),this._committedShowThreads=this.showThreads(),this._instrumentationToolMarshaler.setShowThreadsEnabled({currentShowThreads:e,shouldReanalyze:!1}))))})),this._setupPromise.then((()=>{this._setupPromise=null}))}get dataLoadPromise(){return this._dataLoadPromise?this._dataLoadPromise:Promise.resolve()}get dataLoadStatus(){return this._dataLoadStatus}get resultId(){return this._resultId}get threads(){return this._threads}get threadDomain(){return this._threadDomain}get showThreads(){return this._showThreads}get showJmc(){return this._showJmc}get showNativeCode(){return this._showNativeCode}get showJMCHasFocus(){return this._showJMCHasFocus}get showThreadsHasFocus(){return this._showThreadsHasFocus}get showNativeCodeHasFocusHasFocus(){return this._showNativeCodeHasFocus}get isDefault(){return this._isDefault}get isDisabled(){return this._isDisabled}get selectAll(){return this._selectAll}get selectAllHasFocus(){return this._selectAllHasFocus}get cancelHasFocus(){return this._cancelHasFocus}get filterVisible(){return this._filterVisible}get applyButtonStatus(){return this._applyButtonStatus}dispose(){this._viewEventManager.jmcEnabledStateChanged.removeEventListener(this._onJmcChangedBoundFunction),this._selectAllSubscription.dispose()}onAfterDomInsert(e,t){const i=e[0].parentNode,a=d.Utilities.findChildById(i,"threadFlyout"),o=d.Utilities.findChildById(i,"threadFilterList"),n=()=>{const e=a.offsetHeight-o.clientHeight,t=window.innerHeight-i.offsetHeight-i.offsetTop-e;o.style.maxHeight=`${Math.min(t,175)}px`},l=t.threads.subscribe(n),g=r.eventThrottler(n,h.Constants.WindowResizeThrottle);window.addEventListener("resize",g),s.utils.domNodeDisposal.addDisposeCallback(i,(()=>{window.removeEventListener("resize",g),l.dispose()}))}commitChanges(){this.threads().forEach((e=>e.commitCheck()));const e=this._threads().filter((e=>e.isChecked())).map((e=>e.threadId)),t=e.length===this._threads().length&&this.showJmc();this.isDefault()!==t&&this.isDefault(t);let s=!1;if(this._threadDomain().length!==e.length)s=!0;else{const t=this._threadDomain().slice(0).sort(),i=e.slice(0).sort();for(let e=0;e<t.length;e++)if(t[e]!==i[e]){s=!0;break}}const i=this._committedShowThreads!==this.showThreads(),a=this._committedShowJMC!==this.showJmc(),o=this._committedShowNativeCode!==this.showNativeCode(),n=Promise.resolve(void 0);i&&(this._committedShowThreads=this.showThreads(),n.then((()=>this._instrumentationToolMarshaler.setShowThreadsEnabled({currentShowThreads:this.showThreads(),shouldReanalyze:!a&&!s})))),o&&(this._committedShowNativeCode=this.showNativeCode(),n.then((()=>this._instrumentationToolMarshaler.setNativeCodeFoldingEnabled({currentNativeCodeFolding:!this.showNativeCode(),shouldReanalyze:!a&&!s})))),s&&(this._threadDomain(e),n.then((()=>this._instrumentationToolMarshaler.setThreadSelection({currentThreadDomain:this._threadDomain(),shouldReanalyze:!a})))),a&&n.then((()=>this._dataWarehouse.getJmcService().setJmcEnabledState(this.showJmc()))),this.resetSelectAllUI(e.length===this._threads().length),this.filterVisible(!1)}rollbackChanges(){this.showThreads(this._committedShowThreads),this.showJmc(this._committedShowJMC),this.showNativeCode(this._committedShowNativeCode),this.threads().forEach((e=>e.rollbackCheck()));const e=this._threads().filter((e=>e.isChecked()));this.resetSelectAllUI(e.length===this._threads().length),this.filterVisible(!1)}onResultChanged(e){this._dataLoadCancellationTokenSource&&this._dataLoadCancellationTokenSource.cancel(),this._dataLoadCancellationTokenSource=new c.CancellationTokenSource,this._dataLoadCancellationTokenSource.token.onCancellationRequested.addEventListener((()=>{this._dataLoadStatus(n.DataLoadEvent.DataLoadCanceled)}),{once:!0}),this._dataLoadStatus(n.DataLoadEvent.DataLoadStart);const t=this._dataWarehouse.getResultById(e);this._dataLoadPromise=t.getResult(null,this._dataLoadCancellationTokenSource.token).then((e=>this.addThreads(e))).then((()=>this._instrumentationToolMarshaler.setThreadSelection({currentThreadDomain:this._threadDomain(),shouldReanalyze:!0}))).then((()=>{this._dataLoadStatus(n.DataLoadEvent.DataLoadCompleted)}),(e=>{e.name!==g.errorNameCanceled()&&this._dataLoadStatus(n.DataLoadEvent.DataLoadFailed)}))}addThreads(e){let t=Promise.resolve(void 0);const i=[];return e.forEach((e=>{const t=s.utils.arrayFirst(this._threads(),(t=>t.threadId===e.tid));if(t)t.updateThread(e);else{const t=new a.ThreadViewModel(e,this.isDefault());this._threads.push(t),t.isChecked&&i.push(t.threadId)}})),e.length>0&&(t=this._instrumentationToolMarshaler.isNativeCodeFoldingPersisted().then((e=>{if(!e&&this.threads().length>0){const e=this.threads()[0].isDotNet;this.setDefaultFoldNativeCode(e)}}))),this._threadDomain.valueWillMutate(),i.length>0&&this._threadDomain().push(...i),this._threadDomain.valueHasMutated(),this._threads.sort(((e,t)=>{const s=e=>o.BigNumber.subtract(new o.BigNumber(e.end.h,e.end.l),new o.BigNumber(e.begin.h,e.begin.l));return s(t.dto).greater(s(e.dto))?1:-1})),t}onFocus(){this._currentFocusedIndex=null}onKeyDown(e,t){return u.KeyCodes.ArrowUp===t.keyCode?(this.updateFocusedThread(!1),null===this._currentFocusedIndex||-1===this._currentFocusedIndex?this._currentFocusedIndex=this._threads().length-1:this._currentFocusedIndex=this._currentFocusedIndex-1,this.updateFocusedThread(!0),!1):u.KeyCodes.ArrowDown===t.keyCode?(this.updateFocusedThread(!1),null===this._currentFocusedIndex||this._currentFocusedIndex===this._threads().length-1?this._currentFocusedIndex=-1:this._currentFocusedIndex=this._currentFocusedIndex+1,this.updateFocusedThread(!0),!1):u.KeyCodes.Tab!==t.keyCode||!t.shiftKey||(this._showThreadsHasFocus(!0),!1)}cancelLoading(){this._dataLoadCancellationTokenSource&&this._dataLoadCancellationTokenSource.cancel()}resetSelectAllUI(e){this._selectAllSubscription.dispose(),this.selectAll(e),s.tasks.schedule((()=>{this._selectAllSubscription=this.selectAll.subscribe(this.onSelectAll.bind(this))}))}onCancelKeyDown(e,t){return!(u.KeyCodes.Tab===t.keyCode&&!t.shiftKey&&(this.showJMCHasFocus(!0),1))}onFirstElementKeyDown(e,t){return u.KeyCodes.Tab!==t.keyCode||!t.shiftKey||(this.cancelHasFocus(!0),!1)}onEscKeyDown(e,t){return u.KeyCodes.Escape===t.keyCode&&this.filterVisible()&&(this.rollbackChanges(),this.filterVisible(!1)),!0}updateFocusedThread(e){-1===this._currentFocusedIndex||null===this._currentFocusedIndex||this._currentFocusedIndex>=this._threads().length?this._selectAllHasFocus(e):this._threads()[this._currentFocusedIndex].hasFocus(e)}onSelectAll(e){this._threads().forEach((t=>{t.isChecked(e)}))}onJmcChanged(e){this._committedShowJMC=e.currEnabledState,this.showJmc(e.currEnabledState)}onHeaderKeyDown(e,t){return!!this._isDisabled()||(t.keyCode===u.KeyCodes.ArrowDown?(this.filterVisible(!0),this.showJMCHasFocus(!0),!1):t.keyCode!==u.KeyCodes.Enter||this.toggleFlyout(this,null))}toggleFlyout(e,t){if(this._isDisabled())return!0;const s=this.filterVisible();return s&&this.rollbackChanges(),this.filterVisible(!s),!1}setDefaultFoldNativeCode(e){this.showNativeCode(!e),this._committedShowNativeCode=!e,this._instrumentationToolMarshaler.setNativeCodeFoldingEnabled({currentNativeCodeFolding:e,shouldReanalyze:!1})}}}.apply(t,i),void 0===a||(e.exports=a)},9293:(e,t,s)=>{var i,a;i=[s,t,s(5226),s(3028)],a=function(e,t,s,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.ThreadViewModel=void 0,t.ThreadViewModel=class{constructor(e,t){this._threadId=e.tid,this._isDotNet=e.isDotNet,this.dto=e,this._commitedIsChecked=t,this._isChecked=i.observable(t),this._label=i.pureComputed((()=>this.computeLabel())),this._tooltip=i.pureComputed((()=>this.computeTooltip())),this._hasFocus=i.observable(!1)}get isChecked(){return this._isChecked}get isDotNet(){return this._isDotNet}get hasFocus(){return this._hasFocus}get label(){return this._label}get tooltip(){return this._tooltip}get threadId(){return this._threadId}commitCheck(){this._commitedIsChecked=this.isChecked()}rollbackCheck(){this.isChecked(this._commitedIsChecked)}updateThread(e){e.tid,this.threadId}computeLabel(){return s.Resources.getString("ThreadsSelection_Thread",this.threadId)}computeTooltip(){const e=[];return e.push(s.Resources.getString("ThreadsSelection_Thread",this.threadId)),e.join("\r\n")}}}.apply(t,i),void 0===a||(e.exports=a)},8558:(e,t,s)=>{var i,a;i=[s,t,s(5226),s(3028),s(7886),s(4881),s(8117),s(2560)],a=function(e,t,s,i,a,o,n,l){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.onAfterDomInsert=t.localizeNumber=t.areToolContextsEqual=t.areTimespansEqual=t.areBigNumbersEqual=t.numberComparator=t.getSortFunction=void 0;let r={};s.Culture.addEventListener("culturechanged",(()=>{r={}})),t.getSortFunction=function(e,t){switch(e){case a.SortColumn.Id:return o.SortFunctions.numericSort("id",t);case a.SortColumn.FunctionName:return o.SortFunctions.stringSort("name",t);case a.SortColumn.SelfMetrics:return o.SortFunctions.numericSort("selfMetrics",t);case a.SortColumn.TotalMetrics:return o.SortFunctions.numericSort("totalMetrics",t);case a.SortColumn.ModuleName:return o.SortFunctions.stringSort("moduleName",t);case a.SortColumn.CallCount:return o.SortFunctions.numericSort("callCount",t);case a.SortColumn.AvgSelf:return o.SortFunctions.numericSort("avgSelf",t);case a.SortColumn.AvgTotal:return o.SortFunctions.numericSort("avgTotal",t);case a.SortColumn.MaxSelf:return o.SortFunctions.numericSort("maxSelf",t);case a.SortColumn.MaxTotal:return o.SortFunctions.numericSort("maxTotal",t);case a.SortColumn.MinSelf:return o.SortFunctions.numericSort("minSelf",t);case a.SortColumn.MinTotal:return o.SortFunctions.numericSort("minTotal",t);default:throw n.Assert.fail(`Unknown sort column: ${a.SortColumn[e]}`),new Error(`Unknown sort column: ${a.SortColumn[e]}`)}},t.numberComparator=function(e,t){return e-t},t.areBigNumbersEqual=function(e,t){return!e&&!t||e&&t&&e.h===t.h&&e.l===t.l},t.areTimespansEqual=function(e,t){return!e&&!t||e&&t&&e.equals(t)},t.areToolContextsEqual=function(e,t){return!e&&!t||e&&t&&e.rowId===t.rowId&&e.rowType===t.rowType},t.localizeNumber=function(e,t){const i=JSON.stringify(t||{});let a=r[i];if(!a){const e=new Intl.NumberFormat(s.Culture.formatRegion,t);a=t=>e.format(t),r[i]=a}return a(e)},t.onAfterDomInsert=function(){const e=document.getElementById("mainToolbar"),t=i.utils.domData.get(e,"mediaQuery");if(t){const s=i.utils.domData.get(e,"mediaQueryListener");t.removeListener(s)}let s=45;const a=e.children;for(let e=0;e<a.length;e++)s+=a.item(e).offsetWidth;const o=t=>{t.matches?e.classList.add("limitedSpace"):e.classList.remove("limitedSpace")},n=window.matchMedia(l.Utilities.formatString("(max-width: {0}px)",s.toString()));o(n),n.addListener(o),i.utils.domData.set(e,"mediaQuery",n),i.utils.domData.set(e,"mediaQueryListener",o)}}.apply(t,i),void 0===a||(e.exports=a)},5253:(e,t,s)=>{var i,a;i=[s,t,s(5226)],a=function(e,t,s){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.UtilitiesPortMarshaler=void 0;let i=null;t.UtilitiesPortMarshaler=class{constructor(){null===i&&(i=s.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.Instrumentation.UtilitiesMarshaler",{},!0))}getDoubleClickTimeMs(){return i._call("getDoubleClickTimeMs")}}}.apply(t,i),void 0===a||(e.exports=a)},8117:t=>{"use strict";t.exports=e},2560:e=>{"use strict";e.exports=t},4881:e=>{"use strict";e.exports=s},3028:e=>{"use strict";e.exports=i},5226:e=>{"use strict";e.exports=a}},n={},function e(t){var s=n[t];if(void 0!==s)return s.exports;var i=n[t]={exports:{}};return o[t].call(i.exports,i,i.exports,e),i.exports}(8017);var o,n}));
// SIG // Begin signature block
// SIG // MIIoNwYJKoZIhvcNAQcCoIIoKDCCKCQCAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // QyLF+w+EPBLol1rb2oKvXVrcqh6OqGC4dFqeTXlLVkmg
// SIG // gg2FMIIGAzCCA+ugAwIBAgITMwAAA64tNVHIU49VHQAA
// SIG // AAADrjANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTIzMTExNjE5MDg1OVoX
// SIG // DTI0MTExNDE5MDg1OVowdDELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjEeMBwGA1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // 9CD8pjY3wxCoPmMhOkow7ycCltfqYnqk4wGNApzh2dTY
// SIG // +YqxozWTzJUOB38VxsgFQmXBFhOMdrGYGpvO9kdbNPkw
// SIG // HpTrW6hZqFuLLiRwGKEx4ZM5zVSqbHJuX2fPfUJ0Xmb+
// SIG // VrVsGw/BwBV2zz0rVtiSgqj3GeeGOsG7llfWyrSjyJqm
// SIG // 5DHE3o04BAI/NuhkHOv04euiqJGvHFCL8+fXvyD9OAxq
// SIG // 4fcJKtoyBb0PBA3oMNQeCsiUyLO+voZqVTOUsAWY0bN5
// SIG // YjkK4nq5DVaNdVrrowd5AX9gmz6D/TJTssns6pDCG00Y
// SIG // +Dh3ipWpnVmkhYcByyUSEKX3PLC8DkiAQQIDAQABo4IB
// SIG // gjCCAX4wHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYB
// SIG // BQUHAwMwHQYDVR0OBBYEFIcf73Spl4cHOFoll27H9COd
// SIG // 4fE/MFQGA1UdEQRNMEukSTBHMS0wKwYDVQQLEyRNaWNy
// SIG // b3NvZnQgSXJlbGFuZCBPcGVyYXRpb25zIExpbWl0ZWQx
// SIG // FjAUBgNVBAUTDTIzMDAxMis1MDE4MzYwHwYDVR0jBBgw
// SIG // FoAUSG5k5VAF04KqFzc3IrVtqMp1ApUwVAYDVR0fBE0w
// SIG // SzBJoEegRYZDaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
// SIG // L3BraW9wcy9jcmwvTWljQ29kU2lnUENBMjAxMV8yMDEx
// SIG // LTA3LTA4LmNybDBhBggrBgEFBQcBAQRVMFMwUQYIKwYB
// SIG // BQUHMAKGRWh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9w
// SIG // a2lvcHMvY2VydHMvTWljQ29kU2lnUENBMjAxMV8yMDEx
// SIG // LTA3LTA4LmNydDAMBgNVHRMBAf8EAjAAMA0GCSqGSIb3
// SIG // DQEBCwUAA4ICAQBqyWA1Eu7PKNMjaaxl0V7gJ0XBysUo
// SIG // xZluMHJXFE2LEGZIZ2zMLYVjOnAGG/4dluRjSrZZo/8v
// SIG // wk4Xt8v6NBB9ofo8H1P/XidHytWTv9lg9MYu++6lPmu5
// SIG // fCozD3cI2NLZPW2BBhGX2D0R8tQBj0FbmZRuIucpiQ7D
// SIG // K3CHKlfKcc7MP8pPzuMv55Tox8+KFQD1NG6+bfbYA/BN
// SIG // PBkg4tyOh+exbaHfcNuodDJUIjq9dF6oa+Yjy0u0pUMI
// SIG // /B1t+8m6rJo0KSoZlrpesYl0jRhpt+hmqx8uENXoGJcY
// SIG // ZVJ5N2Skq90LViKNRhi9N4U+e8c4y9uXyomUF/6viCPJ
// SIG // 7huTNEJo75ehIJba+IWd3txUEc0R3y6DT6txC6cW1nR/
// SIG // LTbo9I/8fQq538G5IvJ+e5iSiOSVVkVk0i5m03Awy5E2
// SIG // ZSS4PVdQSCcFxmN4tpEfYuR7AAy/GJVtIDFlUpSgdXok
// SIG // pSui5hYtK1R9enXXvo+U/xGkLRc+qp4De3dZbzu7pOq7
// SIG // V/jCyhuCw0bEIAU4urCGIip7TI6GBRzD7yPzjFIqeZY7
// SIG // S4rVW5BRn2oEqpm8Su6yTIQvMIk8x2pwYNUa2339Z4gW
// SIG // 5xW21eFA5mLpo7NRSKRQms5OgAA18aCgqOU7Ds0h6q/Y
// SIG // B4BmEAtoTMl/TBiyKaMGAlEcdy+5FIhmzojMGjCCB3ow
// SIG // ggVioAMCAQICCmEOkNIAAAAAAAMwDQYJKoZIhvcNAQEL
// SIG // BQAwgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNo
// SIG // aW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQK
// SIG // ExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xMjAwBgNVBAMT
// SIG // KU1pY3Jvc29mdCBSb290IENlcnRpZmljYXRlIEF1dGhv
// SIG // cml0eSAyMDExMB4XDTExMDcwODIwNTkwOVoXDTI2MDcw
// SIG // ODIxMDkwOVowfjELMAkGA1UEBhMCVVMxEzARBgNVBAgT
// SIG // Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAc
// SIG // BgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEoMCYG
// SIG // A1UEAxMfTWljcm9zb2Z0IENvZGUgU2lnbmluZyBQQ0Eg
// SIG // MjAxMTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
// SIG // ggIBAKvw+nIQHC6t2G6qghBNNLrytlghn0IbKmvpWlCq
// SIG // uAY4GgRJun/DDB7dN2vGEtgL8DjCmQawyDnVARQxQtOJ
// SIG // DXlkh36UYCRsr55JnOloXtLfm1OyCizDr9mpK656Ca/X
// SIG // llnKYBoF6WZ26DJSJhIv56sIUM+zRLdd2MQuA3WraPPL
// SIG // bfM6XKEW9Ea64DhkrG5kNXimoGMPLdNAk/jj3gcN1Vx5
// SIG // pUkp5w2+oBN3vpQ97/vjK1oQH01WKKJ6cuASOrdJXtjt
// SIG // 7UORg9l7snuGG9k+sYxd6IlPhBryoS9Z5JA7La4zWMW3
// SIG // Pv4y07MDPbGyr5I4ftKdgCz1TlaRITUlwzluZH9TupwP
// SIG // rRkjhMv0ugOGjfdf8NBSv4yUh7zAIXQlXxgotswnKDgl
// SIG // mDlKNs98sZKuHCOnqWbsYR9q4ShJnV+I4iVd0yFLPlLE
// SIG // tVc/JAPw0XpbL9Uj43BdD1FGd7P4AOG8rAKCX9vAFbO9
// SIG // G9RVS+c5oQ/pI0m8GLhEfEXkwcNyeuBy5yTfv0aZxe/C
// SIG // HFfbg43sTUkwp6uO3+xbn6/83bBm4sGXgXvt1u1L50kp
// SIG // pxMopqd9Z4DmimJ4X7IvhNdXnFy/dygo8e1twyiPLI9A
// SIG // N0/B4YVEicQJTMXUpUMvdJX3bvh4IFgsE11glZo+TzOE
// SIG // 2rCIF96eTvSWsLxGoGyY0uDWiIwLAgMBAAGjggHtMIIB
// SIG // 6TAQBgkrBgEEAYI3FQEEAwIBADAdBgNVHQ4EFgQUSG5k
// SIG // 5VAF04KqFzc3IrVtqMp1ApUwGQYJKwYBBAGCNxQCBAwe
// SIG // CgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB
// SIG // /wQFMAMBAf8wHwYDVR0jBBgwFoAUci06AjGQQ7kUBU7h
// SIG // 6qfHMdEjiTQwWgYDVR0fBFMwUTBPoE2gS4ZJaHR0cDov
// SIG // L2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVj
// SIG // dHMvTWljUm9vQ2VyQXV0MjAxMV8yMDExXzAzXzIyLmNy
// SIG // bDBeBggrBgEFBQcBAQRSMFAwTgYIKwYBBQUHMAKGQmh0
// SIG // dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMv
// SIG // TWljUm9vQ2VyQXV0MjAxMV8yMDExXzAzXzIyLmNydDCB
// SIG // nwYDVR0gBIGXMIGUMIGRBgkrBgEEAYI3LgMwgYMwPwYI
// SIG // KwYBBQUHAgEWM2h0dHA6Ly93d3cubWljcm9zb2Z0LmNv
// SIG // bS9wa2lvcHMvZG9jcy9wcmltYXJ5Y3BzLmh0bTBABggr
// SIG // BgEFBQcCAjA0HjIgHQBMAGUAZwBhAGwAXwBwAG8AbABp
// SIG // AGMAeQBfAHMAdABhAHQAZQBtAGUAbgB0AC4gHTANBgkq
// SIG // hkiG9w0BAQsFAAOCAgEAZ/KGpZjgVHkaLtPYdGcimwuW
// SIG // EeFjkplCln3SeQyQwWVfLiw++MNy0W2D/r4/6ArKO79H
// SIG // qaPzadtjvyI1pZddZYSQfYtGUFXYDJJ80hpLHPM8QotS
// SIG // 0LD9a+M+By4pm+Y9G6XUtR13lDni6WTJRD14eiPzE32m
// SIG // kHSDjfTLJgJGKsKKELukqQUMm+1o+mgulaAqPyprWElj
// SIG // HwlpblqYluSD9MCP80Yr3vw70L01724lruWvJ+3Q3fMO
// SIG // r5kol5hNDj0L8giJ1h/DMhji8MUtzluetEk5CsYKwsat
// SIG // ruWy2dsViFFFWDgycScaf7H0J/jeLDogaZiyWYlobm+n
// SIG // t3TDQAUGpgEqKD6CPxNNZgvAs0314Y9/HG8VfUWnduVA
// SIG // KmWjw11SYobDHWM2l4bf2vP48hahmifhzaWX0O5dY0Hj
// SIG // Wwechz4GdwbRBrF1HxS+YWG18NzGGwS+30HHDiju3mUv
// SIG // 7Jf2oVyW2ADWoUa9WfOXpQlLSBCZgB/QACnFsZulP0V3
// SIG // HjXG0qKin3p6IvpIlR+r+0cjgPWe+L9rt0uX4ut1eBrs
// SIG // 6jeZeRhL/9azI2h15q/6/IvrC4DqaTuv/DDtBEyO3991
// SIG // bWORPdGdVk5Pv4BXIqF4ETIheu9BCrE/+6jMpF3BoYib
// SIG // V3FWTkhFwELJm3ZbCoBIa/15n8G9bW1qyVJzEw16UM0x
// SIG // ghoKMIIaBgIBATCBlTB+MQswCQYDVQQGEwJVUzETMBEG
// SIG // A1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
// SIG // ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBTaWduaW5n
// SIG // IFBDQSAyMDExAhMzAAADri01UchTj1UdAAAAAAOuMA0G
// SIG // CWCGSAFlAwQCAQUAoIGuMBkGCSqGSIb3DQEJAzEMBgor
// SIG // BgEEAYI3AgEEMBwGCisGAQQBgjcCAQsxDjAMBgorBgEE
// SIG // AYI3AgEVMC8GCSqGSIb3DQEJBDEiBCCnAAwzQueTVNK+
// SIG // h2LGu2MwDqkZlNbNMsNFRQMJ/bfB3TBCBgorBgEEAYI3
// SIG // AgEMMTQwMqAUgBIATQBpAGMAcgBvAHMAbwBmAHShGoAY
// SIG // aHR0cDovL3d3dy5taWNyb3NvZnQuY29tMA0GCSqGSIb3
// SIG // DQEBAQUABIIBAE5u5UR4NftCMrH7LCJXweRCVmEG/OPu
// SIG // dl0P8xZ7ek+N/bNnfsXJf/IWD1nscKN/M45Li6MZOaS8
// SIG // sNa2oGt/f148q2RwGvNbooyxK4uauFM9kJC7d8NLfypl
// SIG // cNnldXBgPthAgBYNK/m54uTFnLOIRg1BUSXwHMp63Rcx
// SIG // yZcbx6jrIjFbmw5yTQ21u6t7cBlLl1M4xqCGwMn1l38R
// SIG // tvbO/68f4lG3OKrG8pczMJa72AXWbYV2v6/xWCbMQezF
// SIG // 6FC9IG1m4LsFXFx7SAI/a7cJn+S0L/LGZWJAZomgjERw
// SIG // cpxiBIgdSQoeY2+YS4NpYHsL/RtC5ozTNgmKUydZnElx
// SIG // iJOhgheUMIIXkAYKKwYBBAGCNwMDATGCF4Awghd8Bgkq
// SIG // hkiG9w0BBwKgghdtMIIXaQIBAzEPMA0GCWCGSAFlAwQC
// SIG // AQUAMIIBUgYLKoZIhvcNAQkQAQSgggFBBIIBPTCCATkC
// SIG // AQEGCisGAQQBhFkKAwEwMTANBglghkgBZQMEAgEFAAQg
// SIG // V5ArOpbGiuWR6FfFOnZi/fqXBGSwRgyNLVOV/AGpdq4C
// SIG // BmV7G2lJ1hgTMjAyNDAxMDMxNjAzMTQuMDg1WjAEgAIB
// SIG // 9KCB0aSBzjCByzELMAkGA1UEBhMCVVMxEzARBgNVBAgT
// SIG // Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAc
// SIG // BgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjElMCMG
// SIG // A1UECxMcTWljcm9zb2Z0IEFtZXJpY2EgT3BlcmF0aW9u
// SIG // czEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNOOjk2MDAt
// SIG // MDVFMC1EOTQ3MSUwIwYDVQQDExxNaWNyb3NvZnQgVGlt
// SIG // ZS1TdGFtcCBTZXJ2aWNloIIR6jCCByAwggUIoAMCAQIC
// SIG // EzMAAAHY/EszpR3YhRUAAQAAAdgwDQYJKoZIhvcNAQEL
// SIG // BQAwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hp
// SIG // bmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
// SIG // FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMd
// SIG // TWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAwHhcN
// SIG // MjMwNTI1MTkxMjQwWhcNMjQwMjAxMTkxMjQwWjCByzEL
// SIG // MAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
// SIG // EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jv
// SIG // c29mdCBDb3Jwb3JhdGlvbjElMCMGA1UECxMcTWljcm9z
// SIG // b2Z0IEFtZXJpY2EgT3BlcmF0aW9uczEnMCUGA1UECxMe
// SIG // blNoaWVsZCBUU1MgRVNOOjk2MDAtMDVFMC1EOTQ3MSUw
// SIG // IwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2
// SIG // aWNlMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
// SIG // AgEAzXjrKdH14AM+xlBdDfv9BB3EBa4usJYk25kDZhZv
// SIG // A4tAnkPJ+G3drXebW7c07BJO3WNv55lmPZKhL2r23WEW
// SIG // zXPhLL/DX7+jDCJh/bQq+SsbNueDENI5qUbnK5t7h1uN
// SIG // tQn72tITUBCjdTUtK2ndVP2Tpnvlf0HknViqHwk4cX/3
// SIG // 7E3keNVm6lDQCTf5pd7Gzh/Gi4V8kxxu7Fbf1lEi6U9H
// SIG // y5TV2BkV82rydalDnj88o/OoYiss0CS04yq+xqUxhcko
// SIG // iHDFv58iujSu0Y38taHy3Ub77RyHSb6Zj0s3twh/z2BV
// SIG // NtU6oSIWdfgEu0ZQ6NfDEgxjx6UwlsKO5YLWNaWOkbzy
// SIG // ILhd623bb4aMo5+Zj27OaYIxjvN6HQTT+yJSgI+AWx1F
// SIG // 3h4rdw2toOwOI4nCqyzI6OrBnnrSaHiqKI+YjU12w8Cy
// SIG // jPR5VHV2Us+tn7QmVbivRQYJADvTETdqagZ6bQRn5ZZv
// SIG // ttRS5OhN71VzBhweXjoBXwMvOF5SInsnEAKyA7BJvdih
// SIG // yBThjoGZVsXuvZXl7zB42CZaaNlVTLS8Fy3d7Y0v9e96
// SIG // LhjEWoiyJy5uKCIKg7Y1CKr8GEFId0TesMHRe+Zzpq6a
// SIG // /MEcNZ/wSlkOZoUMWjAaqr5G7rtbC3kjD79jzGSHXVz2
// SIG // 4jrwMWnaj5AXDD1AZq8kmKC08cMCAwEAAaOCAUkwggFF
// SIG // MB0GA1UdDgQWBBT2049MfD2QS2J9DGQSOpxoeaiJVjAf
// SIG // BgNVHSMEGDAWgBSfpxVdAF5iXYP05dJlpxtTNRnpcjBf
// SIG // BgNVHR8EWDBWMFSgUqBQhk5odHRwOi8vd3d3Lm1pY3Jv
// SIG // c29mdC5jb20vcGtpb3BzL2NybC9NaWNyb3NvZnQlMjBU
// SIG // aW1lLVN0YW1wJTIwUENBJTIwMjAxMCgxKS5jcmwwbAYI
// SIG // KwYBBQUHAQEEYDBeMFwGCCsGAQUFBzAChlBodHRwOi8v
// SIG // d3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NlcnRzL01p
// SIG // Y3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0ElMjAyMDEw
// SIG // KDEpLmNydDAMBgNVHRMBAf8EAjAAMBYGA1UdJQEB/wQM
// SIG // MAoGCCsGAQUFBwMIMA4GA1UdDwEB/wQEAwIHgDANBgkq
// SIG // hkiG9w0BAQsFAAOCAgEArpwOmkj+PKCdVQ/kjBdf+0hY
// SIG // kxg+s8iwtybvR7S46mGKtRSVlMddCOV6lNGpXF01BVKF
// SIG // CFD0r33l/3V9DIKH1BvnDl3aJGhx0paOj2SA151ApaZE
// SIG // YsfcQjd+8hQaXMBi8xGZQyiW9oA6vxQRgvLJ05QUhDgY
// SIG // 1dHhPCAlVJDicyALbRMWnkFieUnq1K+t56ul+z5kL5NT
// SIG // ixZdxSaFuPucyqq4mPzyhrLDmgOWYwWRMlPqO/j94nC/
// SIG // 8GdBt8ppU/hGuIfX96uWlXRlQXbIWGv0noRpp1LxjAPI
// SIG // +QrduIp8fm1TrhfxP9i4yKfphGq8uZjk6wDVSi8ptpFt
// SIG // 3kMRfyPXI/O8Z3YmB+eV361jJPW7EU6MTqUW/RKWwgeX
// SIG // Esijb8UPA9NKndk53VRCRaYMgR0CUv1xCuaaHiWeaoJg
// SIG // hQI+FVDwf3T1x3U5tUFySN3Duw0cj1GQGDMENyoT5TNo
// SIG // T9jnwSSK/1bA7Id7Myy9mSbnq47IYcWBlW6DLnfWjaEY
// SIG // 5c9THJ+IhKLWuLWptuBcQ8h66hZuhFELv6Q2BA6rrr0B
// SIG // Rm+YJSHJOKyqgZ0Za0aIkY9KnYTt56KLVYP9Uj9M0ywt
// SIG // Ua8Y7kxFXtzyqxE27b3Dg6Bofddl67X+MGzMKa2vI2LM
// SIG // 8696X9PdOc8y/G/J/JLjAQoQWHxXbPdeik43OExjVPUw
// SIG // ggdxMIIFWaADAgECAhMzAAAAFcXna54Cm0mZAAAAAAAV
// SIG // MA0GCSqGSIb3DQEBCwUAMIGIMQswCQYDVQQGEwJVUzET
// SIG // MBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVk
// SIG // bW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0
// SIG // aW9uMTIwMAYDVQQDEylNaWNyb3NvZnQgUm9vdCBDZXJ0
// SIG // aWZpY2F0ZSBBdXRob3JpdHkgMjAxMDAeFw0yMTA5MzAx
// SIG // ODIyMjVaFw0zMDA5MzAxODMyMjVaMHwxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1l
// SIG // LVN0YW1wIFBDQSAyMDEwMIICIjANBgkqhkiG9w0BAQEF
// SIG // AAOCAg8AMIICCgKCAgEA5OGmTOe0ciELeaLL1yR5vQ7V
// SIG // gtP97pwHB9KpbE51yMo1V/YBf2xK4OK9uT4XYDP/XE/H
// SIG // ZveVU3Fa4n5KWv64NmeFRiMMtY0Tz3cywBAY6GB9alKD
// SIG // RLemjkZrBxTzxXb1hlDcwUTIcVxRMTegCjhuje3XD9gm
// SIG // U3w5YQJ6xKr9cmmvHaus9ja+NSZk2pg7uhp7M62AW36M
// SIG // EBydUv626GIl3GoPz130/o5Tz9bshVZN7928jaTjkY+y
// SIG // OSxRnOlwaQ3KNi1wjjHINSi947SHJMPgyY9+tVSP3PoF
// SIG // VZhtaDuaRr3tpK56KTesy+uDRedGbsoy1cCGMFxPLOJi
// SIG // ss254o2I5JasAUq7vnGpF1tnYN74kpEeHT39IM9zfUGa
// SIG // RnXNxF803RKJ1v2lIH1+/NmeRd+2ci/bfV+Autuqfjbs
// SIG // Nkz2K26oElHovwUDo9Fzpk03dJQcNIIP8BDyt0cY7afo
// SIG // mXw/TNuvXsLz1dhzPUNOwTM5TI4CvEJoLhDqhFFG4tG9
// SIG // ahhaYQFzymeiXtcodgLiMxhy16cg8ML6EgrXY28MyTZk
// SIG // i1ugpoMhXV8wdJGUlNi5UPkLiWHzNgY1GIRH29wb0f2y
// SIG // 1BzFa/ZcUlFdEtsluq9QBXpsxREdcu+N+VLEhReTwDwV
// SIG // 2xo3xwgVGD94q0W29R6HXtqPnhZyacaue7e3PmriLq0C
// SIG // AwEAAaOCAd0wggHZMBIGCSsGAQQBgjcVAQQFAgMBAAEw
// SIG // IwYJKwYBBAGCNxUCBBYEFCqnUv5kxJq+gpE8RjUpzxD/
// SIG // LwTuMB0GA1UdDgQWBBSfpxVdAF5iXYP05dJlpxtTNRnp
// SIG // cjBcBgNVHSAEVTBTMFEGDCsGAQQBgjdMg30BATBBMD8G
// SIG // CCsGAQUFBwIBFjNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
// SIG // b20vcGtpb3BzL0RvY3MvUmVwb3NpdG9yeS5odG0wEwYD
// SIG // VR0lBAwwCgYIKwYBBQUHAwgwGQYJKwYBBAGCNxQCBAwe
// SIG // CgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB
// SIG // /wQFMAMBAf8wHwYDVR0jBBgwFoAU1fZWy4/oolxiaNE9
// SIG // lJBb186aGMQwVgYDVR0fBE8wTTBLoEmgR4ZFaHR0cDov
// SIG // L2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVj
// SIG // dHMvTWljUm9vQ2VyQXV0XzIwMTAtMDYtMjMuY3JsMFoG
// SIG // CCsGAQUFBwEBBE4wTDBKBggrBgEFBQcwAoY+aHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNS
// SIG // b29DZXJBdXRfMjAxMC0wNi0yMy5jcnQwDQYJKoZIhvcN
// SIG // AQELBQADggIBAJ1VffwqreEsH2cBMSRb4Z5yS/ypb+pc
// SIG // FLY+TkdkeLEGk5c9MTO1OdfCcTY/2mRsfNB1OW27DzHk
// SIG // wo/7bNGhlBgi7ulmZzpTTd2YurYeeNg2LpypglYAA7AF
// SIG // vonoaeC6Ce5732pvvinLbtg/SHUB2RjebYIM9W0jVOR4
// SIG // U3UkV7ndn/OOPcbzaN9l9qRWqveVtihVJ9AkvUCgvxm2
// SIG // EhIRXT0n4ECWOKz3+SmJw7wXsFSFQrP8DJ6LGYnn8Atq
// SIG // gcKBGUIZUnWKNsIdw2FzLixre24/LAl4FOmRsqlb30mj
// SIG // dAy87JGA0j3mSj5mO0+7hvoyGtmW9I/2kQH2zsZ0/fZM
// SIG // cm8Qq3UwxTSwethQ/gpY3UA8x1RtnWN0SCyxTkctwRQE
// SIG // cb9k+SS+c23Kjgm9swFXSVRk2XPXfx5bRAGOWhmRaw2f
// SIG // pCjcZxkoJLo4S5pu+yFUa2pFEUep8beuyOiJXk+d0tBM
// SIG // drVXVAmxaQFEfnyhYWxz/gq77EFmPWn9y8FBSX5+k77L
// SIG // +DvktxW/tM4+pTFRhLy/AsGConsXHRWJjXD+57XQKBqJ
// SIG // C4822rpM+Zv/Cuk0+CQ1ZyvgDbjmjJnW4SLq8CdCPSWU
// SIG // 5nR0W2rRnj7tfqAxM328y+l7vzhwRNGQ8cirOoo6CGJ/
// SIG // 2XBjU02N7oJtpQUQwXEGahC0HVUzWLOhcGbyoYIDTTCC
// SIG // AjUCAQEwgfmhgdGkgc4wgcsxCzAJBgNVBAYTAlVTMRMw
// SIG // EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
// SIG // b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
// SIG // b24xJTAjBgNVBAsTHE1pY3Jvc29mdCBBbWVyaWNhIE9w
// SIG // ZXJhdGlvbnMxJzAlBgNVBAsTHm5TaGllbGQgVFNTIEVT
// SIG // Tjo5NjAwLTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9z
// SIG // b2Z0IFRpbWUtU3RhbXAgU2VydmljZaIjCgEBMAcGBSsO
// SIG // AwIaAxUASKfvsVCfn/OVa5283ZETEqQZry+ggYMwgYCk
// SIG // fjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
// SIG // Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
// SIG // TWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1N
// SIG // aWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDANBgkq
// SIG // hkiG9w0BAQsFAAIFAOk/9vMwIhgPMjAyNDAxMDMxNTA4
// SIG // MzVaGA8yMDI0MDEwNDE1MDgzNVowdDA6BgorBgEEAYRZ
// SIG // CgQBMSwwKjAKAgUA6T/28wIBADAHAgEAAgItUTAHAgEA
// SIG // AgITmTAKAgUA6UFIcwIBADA2BgorBgEEAYRZCgQCMSgw
// SIG // JjAMBgorBgEEAYRZCgMCoAowCAIBAAIDB6EgoQowCAIB
// SIG // AAIDAYagMA0GCSqGSIb3DQEBCwUAA4IBAQCXOV9Dtfrw
// SIG // RjZN7Trp2g8+ivkJyVGNu0mxh7x/u5XwFHje56OXeAiy
// SIG // 2DpuqBs+DD9L4GOEvU7oj3lO+Jt6xzB/3qNo+rZLAi20
// SIG // 5T9cgYaWp+/WeYUjag+m1SPEApWcVpf5pyn47rSEGsbB
// SIG // GnEPPAVlGJyKuwxNYbCsopJ2TqnpAHrVRfOksViWH4Yt
// SIG // 1Pgx+SWACiBdlVuUCqkqtkN3kf19slsXrqrcVroHW2I3
// SIG // 22/H/QnmxMXEnf0EEUdLiYS3LutBgKIiQPn8ekdcEtz6
// SIG // GMShVedaTLmtTuxrcNdpTMdaN0PlvAE7RleqBqnfDuVK
// SIG // +ROaNG8HVYkuhYWU25Hd9BL6MYIEDTCCBAkCAQEwgZMw
// SIG // fDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
// SIG // b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
// SIG // Y3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWlj
// SIG // cm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTACEzMAAAHY
// SIG // /EszpR3YhRUAAQAAAdgwDQYJYIZIAWUDBAIBBQCgggFK
// SIG // MBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAvBgkq
// SIG // hkiG9w0BCQQxIgQgztm7Rpwf4YA7bp8CAD2wXJqpWCaf
// SIG // TwGyz3uA4TGUrxQwgfoGCyqGSIb3DQEJEAIvMYHqMIHn
// SIG // MIHkMIG9BCA64yF//AmTd0UwATDbebu9zIt6N35r6to/
// SIG // EopPtrO+VDCBmDCBgKR+MHwxCzAJBgNVBAYTAlVTMRMw
// SIG // EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
// SIG // b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
// SIG // b24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1w
// SIG // IFBDQSAyMDEwAhMzAAAB2PxLM6Ud2IUVAAEAAAHYMCIE
// SIG // IMufw1yWnyYJANbopin6DD3/mX5ULRPh2S35T3jwQVdb
// SIG // MA0GCSqGSIb3DQEBCwUABIICAJhf81k3xjWz2o1DQOoK
// SIG // WTZpUFFtaN/L3Np+ybXjV7FDVqu4ljZ1g8ak71cI4xls
// SIG // zrpeteogYJzmD80z1492eJ5Zat/PHbzPTqOSqiwsYp4y
// SIG // sOeOYsEGN8WBJSpq+Ojzr+4goBJjKmRDBI8kAClWOr5r
// SIG // ySao69w/vXSExckn9h+RpVe2tnMCHu9xExHIchhUxnPM
// SIG // lFMxksFlqg4u9/RQ2Hz5+9IaUoJ/W8TL/XrBF783xcab
// SIG // 9aYY5ZjBdaz+7CEX3XWrQLLWPqWtK8ZNiN2LGWeYCXl6
// SIG // l01+4R9qv72bZ8QMO6JTkHpjO/i5xzmqg3J5TqZrz8k0
// SIG // si3OsyrDpx0RbbF8aFih7eCYlKteNWNxab8r+kqled90
// SIG // vPY9PNeslCaqKkWn+zzbfa5SfsCHhL1/hhnx4pB9W3/p
// SIG // yuDvnMeeYFu+fk32Z/SGalofCzVdT0pkLg0lboFlg8wQ
// SIG // 5bHO6EgzlzoiGeDMwwq5xQIqdHXBz/a+CZMICdc19xET
// SIG // WONGbGbzPHQmDHKSK0cREvrZD8vX+KEAPWW/4IFDpqdN
// SIG // xLHzB2DZnfHi5YRPyueUHpYiIeJmm8/0cDJyxnUleYnc
// SIG // wXwgLSVcr25JbADWQbKxHXWXYRoK4IFsQ32BbVKs8FFB
// SIG // Ln/eDUAuYWt1KVz/CljNToZXYOQO6a+F6QEQtP8bg76Y
// SIG // mXgG
// SIG // End signature block
